### PR TITLE
Added Global Styling Guideline

### LINKED ISSUE #714: Create a Contribution Guideline for Python
## Description 

Create a Contribution Guideline for Python. The Contribution Guideline should help new Contributors to understand all the necessary steps before raising a PR. It should broadly cover these parts: 

- Using tools like PyLint for Code Quality Check 
- Making proper directories, naming conventions and making the Python README changes
- Adding Screenshot Images through Imgur 
- Formatting the Script README for a better purpose
- Usage of `.env` for API Keys and making proper commits 

The Doc should be named as `CONTRIBUTION-GUIDELINE.md` and would live in the Python directory. Adding screenshots for the above points would be helpful, but not needed.

### PR DESCRIPTION
**Pull request by vybhav72954**
# Description

@HarshCasper This is kind of an incomplete PR (will make this draft), but here is the backbone of the styling guideline. I will make a few more changes and upload 2 new files (most probably).

Meanwhile, you can read this and suggest me changes.

Fixes #714 

Update - **Open for Review**

## Type of change

- [x] Documentation Update

### CODE REVIEW

**Comment by vybhav72954** [comment]
# TODO

- [ ] Update every link
- [ ] Changes in CONTRIBUTING.md
- [ ] Chnages in Troubleshoot.md
- [ ] JavaScript Guide
- [ ] Python CONTRIBUTING GUIDE
- [ ] Recheck the code fence and blanklines
- [ ] Extra Whitespaces

**Comment by vybhav72954** [comment]
I have added all the files, the links are not working properly (would edit them tomorrow), but the basic structure is up for review.

**Comment by vybhav72954** [comment]
@HarshCasper I have updated all the files accordingly, there are no error in Markdwon Lint Action apart from inline HTML, (used in various places).

The guides are as thorough as possible, that's why it took way too long then expected, but I believe that I haven't missed any point.



> * [x]  Update every link
> * [x]  Changes in CONTRIBUTING.md
> * [x]  Chnages in Troubleshoot.md
> * [ ]  JavaScript Guide
> * [x]  Python CONTRIBUTING GUIDE
> * [x]  Recheck the code fence and blanklines
> * [x]  Extra Whitespaces
> * [x]  Changes according to the Action
> * [ ]  Emojis?
> * [x]  Interlinking

As you can check the TODO list, JS styling guidelines are missing cause am not the best person to do that, also I haven't added a whole lot of emojis, I can if you want though :)


Hopefully this will help the Repo

**Review by HarshCasper — APPROVED** [review]
Thanks a lot!

**Comment by vybhav72954** [comment]
I haveone suggestion though, in Python->README, 
we should remove the Serial Number thing, it would be better
as changing numbers manually in order to maintain the alphabetical structure is a hassle

**Comment by HarshCasper** [comment]
> I haveone suggestion though, in Python->README,
> we should remove the Serial Number thing, it would be better
> as changing numbers manually in order to maintain the alphabetical structure is a hassle

Yeah. Can you create an Issue for the same? Let's see if some new contributors would like to take it up

**Pull request merged**
