### PR TITLE
Internet Speed Test in CLI

### LINKED ISSUE #1137: Internet speed test in Python
# Description

Hey @HarshCasper 
I would like to add internet speed test in python using simple cli.
Please assign it to me.
Thanks

## Language

- [ ] Go
- [ ] Javascript
- [x] Python
- [ ] Other (Please specify)

## Checklist:

- **Details on the Script**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Name of Script | Details of the script | feature (You can add acronyms of open source events as well) | self-assign if you want to work on this issue else leave blank |

**Is your feature request related to a problem? Please describe.**: 

**Describe the solution you'd like**: 

**Additional context**:

### PR DESCRIPTION
**Pull request by Shaishav0507**
# Description

Hey @HarshCasper 
Added Internet speed test in python using CLI
Please check and update.
Thanks

Fixes #1137 

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [x] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by iamakkkhil** [comment]
Hey @Shaishav0507, can you please create a README.md and requirements.txt file so that anyone can understand how to use your code. Other than this you can create a function which can be called using main() and embed your image in README only by using imgur.

**Comment by iamakkkhil** [comment]
Looks good, just make the requested changes

**Comment by iamakkkhil** [comment]
Are you a participant of LGMSoC ?

**Comment by Shaishav0507** [comment]
> Are you a participant of LGMSoC ?

Yes, I'll do the changes

**Comment by Shaishav0507** [comment]
@iamakkkhil Done with the changes.
Please check

**Comment by RohiniRG** [comment]
This script seems a little less intuitive as compared to the scripts already present in the repo. The script is pretty basic and it just imports a module and uses its methods. This is not what we are looking for, so I'll be closing this PR.
Thank you for your contribution!

**Pull request closed without merging**
