### PR TITLE
Make linguist ignore *.ipynb files

### LINKED ISSUE #809: Preventing reporting the Project as a "Jupyter Notebook" Repo
## Description 

Majority of the Scripts on the project are either in Python, Javascript and Golang. Some of the contributors started contributing Jupyter Notebooks as well, in a bid to have a better visualization for the scripts that they wrote. It not only enhanced the understanding for a user but for scripts that relied on AI/ML, it gave a better insight into the functionality.

However, Jupyter Notebooks are notorious to have a lot of metadata associated with the files. And now with a lot of Notebooks, there are a lot of metadata and it has inflated the lines of code so much, that the project is now classified in `Jupyter Notebook` category. 

This behaviour can be fixed, by adding a  `*.ipynb linguist-vendored` to the `.gitattributes` file.

### PR DESCRIPTION
**Pull request by pganguli**
# Description

Making linguist ignore *.ipynb files for language classification can prevent GitHub from incorrectly classifying this repo as a Jupyter Notebook repo.

Fixes #809 

## Type of change

Added a .gitattribute file in the Python directory.

- [X] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [X] My code follows the style guidelines(Clean Code) of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by pganguli** [comment]
@HarshCasper I see that the GitHub greeting 'check' that greets new pull requesters fails with an error for all recent pull requests. Can you please have a look at it?
Also, the spell checker incorrectly classifies some html formatted text as 'misspellings'. Again, as a maintainer of this project, maybe you can make it ignore the files in question?

**Comment by HarshCasper** [comment]
We will review the PR once the GSSoC '21 Coding period starts. Thanks!

**Comment by pganguli** [comment]
Applied the new gitattributes repo-wide, instead of being specific to /Python

**Review by vybhav72954 — APPROVED** [review]

**Review by vybhav72954 — APPROVED** [review]

**Comment by vybhav72954** [comment]
@HarshCasper Is this actually working?

**Comment by HarshCasper** [comment]
> @HarshCasper Is this actually working?

I believe yes.

**Pull request merged**
