### PR TITLE
Website for this project

### LINKED ISSUE #656: Creating a SSG website for this project.
Hello @HarshCasper, 

There are lots of SSGs, some of the most popular are Sphinx, Jekyll, and a lot [more](https://scotch.io/tutorials/top-10-static-site-generators-in-2020). More or less they work on the same principle, that is converting Markdown or reStructured Text into HTML.

You may choose any SSG, but Jekyll has an additional advantage that it works natively with gh-pages, no CI/CD required. There are a plethora of themes. As per my experience, I can suggest two ways to create a website for this project.
1. Since every script in this project has a separate readme file. we can just modify them a bit to be included by the site generator recursively (just adding few keywords) and thus site will be generated, you can customize the home page. 
2. Create a whole new branch/repo for this purpose and add each script description separately. This gives us slightly more control but it needs huge efforts.

For example you can see these:-
- source: https://code.videolan.org/avinal/vlc-android-user generated-site: https://avinal.videolan.me/vlc-android-user (sphinx)
- https://avinal.is-a.dev (pelican)
- https://idratherbewriting.com/documentation-theme-jekyll/ (Jekyll)

### PR DESCRIPTION
**Pull request by avinal**
# Description

- All the readme markdown files has been changed to restructuredtext to better suit with sphinx and will also prove more powerful syntax for the repository itself
- Page publishing action has been added
- Markdown files have been removed
- Scripts file has not been touched
- `Check it out` badge added to each readme

Check current deployment at https://avinal.space/Rotten-Scripts/

Fixes #656 
 See Discussions at #755 
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [x] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by avinal** [comment]
Hello @HarshCasper, I know this is a very large change to merge, so we may have a review period of 2-3 weeks, and I am happy to resolve any conflicts, (may need permission to the repo).

**Comment by HarshCasper** [comment]
> Hello @HarshCasper, I know this is a very large change to merge, so we may have a review period of 2-3 weeks, and I am happy to resolve any conflicts, (may need permission to the repo).

Sure. Can you please drop me a mail [here](mailto:erbeusgriffincasper@gmail.com) and I will share the due permissions sure after. It will take at least a week for review and we can hopefully deploy it this week.

**Comment by HarshCasper** [comment]
> > Hello @HarshCasper, I know this is a very large change to merge, so we may have a review period of 2-3 weeks, and I am happy to resolve any conflicts, (may need permission to the repo).
> 
> Sure. Can you please drop me a mail [here](mailto:erbeusgriffincasper@gmail.com) and I will share the due permissions sure after. It will take at least a week for review and we can hopefully deploy it this week.

Tagging @vybhav72954 and @seema1711 who might be able to help us with the review.

**Comment by avinal** [comment]
> > > Hello @HarshCasper, I know this is a very large change to merge, so we may have a review period of 2-3 weeks, and I am happy to resolve any conflicts, (may need permission to the repo).
> > 
> > Sure. Can you please drop me a mail [here](mailto:erbeusgriffincasper@gmail.com) and I will share the due permissions sure after. It will take at least a week for review and we can hopefully deploy it this week.
> 
> Tagging @vybhav72954 and @seema1711 who might be able to help us with the review.

Feel free to ask doubts about restructuredtext and sphinx syntax, Its mostly similar to markdown, should be easier to catch up for you guys. Again in any case I am just a ping away.

**Comment by vybhav72954** [comment]
@avinal @HarshCasper @seema1711  Let's do this 🤩

**Comment by HarshCasper** [comment]
@vybhav72954 and @avinal : I will share the collaborator access to both of you for the repository. Since I have both of your Mail IDs, I can setup some day to have a short call ( ~15 mins) so that we can start reviewing it up.

**Comment by avinal** [comment]
Yeah sure, we can have a meet. 🤩

**Comment by avinal** [comment]
The pull request was not reviewed in 3 months. It is stale and unusable now. 👎🏼

**Comment by vybhav72954** [comment]
> The pull request was not reviewed in 3 months. It is stale and unusable now. Closing it for good.👎🏼

Hey Avinal, thank you so much for your time. During GSSoC, because of an upsurge in participants, we were not able to look into it. The website project is still in the back of our mind, possibly after GSSoC we can start everything together once again.

**Comment by HarshCasper** [comment]
> The pull request was not reviewed in 3 months. It is stale and unusable now. Closing it for good.👎🏼

Hello @avinal 

We are sorry for this experience and truly believe that you worked quite hard on it. We have kick-started the development of a new website and we would use your pull request as a base to start the work from. Thanks for all your contributions and appreciate your work over the same. We have been at fault of not being able to merge it earlier due to GSSoC and other personal commitments.

**Pull request closed without merging**
