### PR TITLE
Hitesh pdf generator

### PR DESCRIPTION
**Pull request by HeroicHitesh**
Resolves issue #34 
PR includes the script, it's ss and README.md to explain how to use the script.

### CODE REVIEW

**Comment by HarshCasper** [comment]
Are you working on adding the changes I mentioned?

**Comment by HeroicHitesh** [comment]
Yes, I was busy with some work, will try to complete it in a day or two.

**Comment by HarshCasper** [comment]
@HeroicHitesh Are you still working on this?

**Comment by HeroicHitesh** [comment]
Yes, I will try to complete this by today itself. I am sorry for the delay.

**Pull request closed without merging**
