### PR TITLE
Updated PDF merger

### LINKED ISSUE #604: Merge Pdf using pyPDF
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
A python script which takes pdf file as input and merges them using pyPDF module

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by Aayush-hub**
# Description

Added a Pdf merger using python. It is very short and readable code. User can merge lots (as he desire) of PDF's in one go, without wasting any time seeing every page and every PDF. User didn't need to type name of every PDF to merge, he/she can arrange PDF's with a default name with numbers after that.
Like if user want to merge 100 PDF's then he can name PDF's as PDF1,PDF2,PDF3............PDF100, and the code will merge them in one go and need not require naming every PDF in code to merge.

Fixes #604 Merge Pdf using pyPDF

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

# Screenshots
- Input-1 
Capture
- Input 2
Capture2
- Output
Capture3

### CODE REVIEW

**Comment by Aayush-hub** [comment]
@HarshCasper Sir, please review my PR as NWOC participant:)

**Comment by HarshCasper** [comment]
Hi @Aayush-hub 

A PR for the issue has already been raised and merged here: https://github.com/HarshCasper/Rotten-Scripts/pull/611

**Comment by Aayush-hub** [comment]
@HarshCasper Sir, I have seen that but I have improved the functionality, speed of merger process and issue is not closed yet, so I request you to review changes made by me once.

**Comment by HarshCasper** [comment]
Since the PR for the Issue has already been merged, I would request you to kindly improve the existing Code, if you can. We cannot have duplicated scripts in any case.

**Comment by Aayush-hub** [comment]
@HarshCasper okay sir!

**Comment by HarshCasper** [comment]
> @HarshCasper okay sir!

Ain't no, Sir. We all are good friends here :)

**Pull request closed without merging**
