### PR TITLE
Internet Speed Test in Python

### LINKED ISSUE #1122: Internet Speed Test in Python
# Description

Hey @HarshCasper 
I would like to add Internet speed test code in python, where it will do the speed test.
Please assign it to me.
Thanks

## Language

- [ ] Go
- [ ] Javascript
- [x] Python
- [ ] Other (Please specify)

## Checklist:

- **Details on the Script**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Name of Script | Details of the script | feature (You can add acronyms of open source events as well) | self-assign if you want to work on this issue else leave blank |

**Is your feature request related to a problem? Please describe.**: 

**Describe the solution you'd like**: 

**Additional context**:

### PR DESCRIPTION
**Pull request by Shaishav0507**
# Description

Fixes #1122 
Hey @HarshCasper 
Added the code for internet speed test in Python.
Please check and Update
Thanks

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by HarshCasper — CHANGES_REQUESTED** [review]
We don't accept GUI Apps. Thanks for your contribution!

**Comment by Shaishav0507** [comment]
> We don't accept GUI Apps. Thanks for your contribution!

Without gui will work or not

**Comment by Shaishav0507** [comment]
@HarshCasper 
I have without GUI also.
If you want ?

**Comment by HarshCasper** [comment]
> @HarshCasper
> I have without GUI also.
> If you want ?

A CLI App would work fine.

**Comment by Shaishav0507** [comment]
> > @HarshCasper
> > I have without GUI also.
> > If you want ?
> 
> A CLI App would work fine.

Ok I'll add

**Comment by Shaishav0507** [comment]
Open the issue

**Comment by Shaishav0507** [comment]
@HarshCasper 
Please reopen the issue, I'll add than.

**Comment by Shaishav0507** [comment]
@HarshCasper 
Reopen the issue so that I can add.

**Pull request closed without merging**
