### PR TITLE
Image filters using 3Dimensional convolution

### PR DESCRIPTION
**Pull request by Namyalg**

### CODE REVIEW

**Comment by HarshCasper** [comment]
Hello @Namyalg 

Can you please create an Issue for this Pull Request so that it is easy for us to manage the Scores and take care of the Scripts that we have added in the Repo ?

**Comment by Namyalg** [comment]
Okay, I will create an issue.

**Comment by HarshCasper** [comment]
Hello @Namyalg 

Can you please work on improving your `README` Documentation. It is blurry and does not give much information on what the Script does.

**Comment by Namyalg** [comment]
Okay, I will improve the documentation and also share the link to the blog
I have written on it.

**Comment by Namyalg** [comment]
Hi Harsh,
This is a link to the medium blog on 3D convolution. Wanted to know if I
can add this in the README
https://medium.com/@namyalg/3-dimensional-convolution-7041ca7f3e81?source=friends_link&sk=3e78081075504e2a4716628b09ad5559

Regards,
Namya

**Comment by HarshCasper** [comment]
Hello @Namyalg 

You can definitely proceed with adding this Blog in your README

**Comment by Namyalg** [comment]
I have updated the README file

**Comment by HarshCasper** [comment]
Reviewed and Merged 💥

Thanks for your Contribution 🎉

**Pull request merged**
