### PR TITLE
Send E-Mails through the G-Mail REST API via OAuth 2.0

### LINKED ISSUE #588: Send E-Mails through the G-Mail REST API via OAuth 2.0
## Description 

Send E-Mails through the G-Mail REST API via OAuth 2.0

* Obtain a Gmail user's credentials using OAuth 2.0. The OAuth 2.0 process should be initiated by an API call to your server.
* Store the obtained credentials in a file.
* Have a Script to execute send email using the credentials previously stored.

## Languages 

- Python
- Javascript

### PR DESCRIPTION
**Pull request by Sumit-Sahu**
# Description
script to authenticate user via OAuth 2.0 and send email by gmail api.
Fixes #588 

## Type of change
- [x] New feature (non-breaking change which adds functionality

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Sumit-Sahu** [comment]
@HarshCasper Here is link for hosted site. https://testapi.pythonanywhere.com/

**Comment by HarshCasper** [comment]
Hi @Sumit-Sahu 

Thanks for raising the PR! We don't support Web Application as of yet. 

Through this Project we are looking for Scripts and not Web Applications. Unfortunately, I will not be able to merge this PR. 

If you would still like to continue on this, please make a Script with some Arg Parsers to pass on the information through a CLI and not an Application. Let me know what you think about this!

**Comment by Sumit-Sahu** [comment]
hi @HarshCasper I have created new folder and pushed my commits their.
Any idea how can I remove previous folder.
If I simply delete and push again then folder still exist in commit history??

**Comment by HarshCasper** [comment]
Hello @Sumit-Sahu 

Please delete the Folder and then squash your Commits. Its pretty easy.

Let's say: there were 5 commits in total:
- `git reset --soft HEAD~5` will soft reset the last 5 commits.
- Make a single commit with `git add` and `git commit`
- And after that, `git push -f origin HEAD` will force push the single commit.

**Comment by Sumit-Sahu** [comment]
@HarshCasper  done.

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Remove the Token. Rest looks good to me 👍 

If possible, please add a GIF as well to show your Script is working. Once done, please mention me here and I will merge it.

**Comment by Sumit-Sahu** [comment]
@HarshCasper  done.

**Comment by HarshCasper** [comment]
LGTM! Thanks 🚀

**Pull request merged**
