### PR TITLE
Twitter bookmarks

### PR DESCRIPTION
**Pull request by Blastoise**
Added Bash Script for scraping the URL's of the tweets saved as Twitter Bookmark and saving them in a markdown file.

Fixes #(538)

## Type of change

- [ x ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ x ] My code follows the style guidelines(Clean Code) of this project
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] I have created a helpful and easy to understand `README.md`
- [ x ] I have made corresponding changes to the documentation
- [ x ] My changes generate no new warnings
- [ x ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by HarshCasper** [comment]
One Question: Does the Script save Twitter Bookmarks or a Browser Bookmark? Because I see the later happening up. If that's the case, can you create an Issue, because the Issue is interesting and I would like it to be part of it.

**Comment by Blastoise** [comment]
@HarshCasper  Actually I made this branch from the which had Broswer Bookmarks, so there are two Bash Scripts in this Branch.
Twitter Bookmarks saves the Twitter Bookmarks and Bookmarks Keeper saves the bookmarks from all the Browser present on the system.
Yes i have opened an issue on Broswer Bookmarks.

**Comment by HarshCasper** [comment]
> @HarshCasper Actually I made this branch from the branch which had Broswer Bookmarks, so there are two Bash Scripts in this Branch.
> Twitter Bookmarks saves the Twitter Bookmarks and Bookmarks Keeper saves the bookmarks from all the Browser present on the system.
> Yes i have opened an issue on Broswer Bookmarks.

Can you make two separate branches and then the PRs from the same?

**Comment by Blastoise** [comment]
> > @HarshCasper Actually I made this branch from the branch which had Broswer Bookmarks, so there are two Bash Scripts in this Branch.
> > Twitter Bookmarks saves the Twitter Bookmarks and Bookmarks Keeper saves the bookmarks from all the Browser present on the system.
> > Yes i have opened an issue on Broswer Bookmarks.
> 
> Can you make two separate branches and then the PRs from the same?

Yes give me a minute

**Pull request closed without merging**
