### PR TITLE
Pr152

### LINKED ISSUE #152: Script to merge PDF files
# Description

Develop a script for merging PDF files. 

## Language

- [x] Python

## Type of issue

- [x] Feature

## Checklist:

- **For Feature**

|name|about|labels|assignees|
|----|-----|------|---------|
|Merge PDF files|We have many PDF files of our course at college |Python| |

**Is your feature request related to a problem? Please describe.**: We generally have many PDF files related to the same subject of our course. So why not simply merge them into one and get rid of finding them every time we need it?

# Update

The script is open to all in Golang and JavaScript.

For python we have a script [here](https://github.com/HarshCasper/Rotten-Scripts/tree/master/Python/Merge_2_PDFs). Kindly suggest improvements then only this can be assigned to you 😄

### PR DESCRIPTION
**Pull request by harshita2319**
# Description

I've added the code to merge two pdfs using javascript. 
Folder name: Merge_pdfs.
I've added the code, readme file and the pdfs used along with the screenshots.

Fixes #152

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by vybhav72954** [comment]
@sohamsshah

**Review by vybhav72954 — COMMENTED** [review]
Code looks plagiarised from [here](https://thecodebarbarian.com/working-with-pdfs-in-node-js.html).

**Comment by harshita2319** [comment]
> Code looks plagiarised from [here](https://thecodebarbarian.com/working-with-pdfs-in-node-js.html).

Hey, I pushed this file today morning from old resources unknowingly and from then I've been trying to incorporate the new file to this pr but I'm not able to. 

You may assign this issue to someone else if you feel so but I would really appreciate if you can help me with this, I'm new to open source.

**Comment by vybhav72954** [comment]
> > Code looks plagiarised from [here](https://thecodebarbarian.com/working-with-pdfs-in-node-js.html).
> 
> Hey, I pushed this file today morning from old resources unknowingly and from then I've been trying to incorporate the new file to this pr but I'm not able to.
> 
> You may assign this issue to someone else if you feel so but I would really appreciate if you can help me with this, I'm new to open source.

No problem, We are here to help only. You need not worry.

In your case. You can do 2 things.

1. Close this PR. Make a new branch from **master**. Commit the new files in that branch, make a new PR. (recommended)
2. Stay in the same branch from which you made this PR. Delete your useless files, Rebase commit back to original head. Commit new files. Push them.

**Comment by harshita2319** [comment]
> > > Code looks plagiarised from [here](https://thecodebarbarian.com/working-with-pdfs-in-node-js.html).
> > 
> > Hey, I pushed this file today morning from old resources unknowingly and from then I've been trying to incorporate the new file to this pr but I'm not able to.
> > 
> > You may assign this issue to someone else if you feel so but I would really appreciate if you can help me with this, I'm new to open source.
> 
> No problem, We are here to help only. You need not worry.
> 
> In your case. You can do 2 things.
> 
> 1. Close this PR. Make a new branch from **master**. Commit the new files in that branch, make a new PR. (recommended)
> 2. Stay in the same branch from which you made this PR. Delete your useless files, Rebase commit back to original head. Commit new files. Push them.
> 
> 

Yeah I was trying the second one and messed up badly.
Dk why I thought that we can't directly delete a pr, I'll go with this.
 
Thanks for helping!
Also, now can I work on this issue again?

**Comment by vybhav72954** [comment]
> > > > Code looks plagiarised from [here](https://thecodebarbarian.com/working-with-pdfs-in-node-js.html).
> > > 
> > > 
> > > Hey, I pushed this file today morning from old resources unknowingly and from then I've been trying to incorporate the new file to this pr but I'm not able to.
> > > You may assign this issue to someone else if you feel so but I would really appreciate if you can help me with this, I'm new to open source.
> > 
> > 
> > No problem, We are here to help only. You need not worry.
> > In your case. You can do 2 things.
> > 
> > 1. Close this PR. Make a new branch from **master**. Commit the new files in that branch, make a new PR. (recommended)
> > 2. Stay in the same branch from which you made this PR. Delete your useless files, Rebase commit back to original head. Commit new files. Push them.
> 
> Yeah I was trying the second one and messed up badly.
> Dk why I thought that we can't directly delete a pr, I'll go with this.
> 
> Thanks for helping!
> Also, now can I work on this issue again?

Just delete this PR, make a new one for the same issue. In case of any other problem, you can ping me or any maintainer here only!!!

**Pull request closed without merging**
