### PR TITLE
Created a Python Script to Generate Environment Variables

### LINKED ISSUE #423: Python Script to find all Environment Variables in a Codebase
# Description

Create a Python Script to find all Environment Variables in a Codebase. It is usual to entirely forget about documenting the Environment Variables in your Project. Your Script should parse the entire codebase and find all the necessary environment variables and create a `env.example` file as the output.

## Language

- [X] Python

## Type of issue

_Please delete options that are not relevant._

- [X] Feature

### PR DESCRIPTION
**Pull request by agrima84**
# Description

A Python Script which generates a new file containing all the environment variables used in the codebase.
Fixes #423

### CODE REVIEW

**Comment by HarshCasper** [comment]
Can you explain to me what does your Script does?

**Comment by agrima84** [comment]
The script creates a new file which contains all the environment variables (its name and value) .
am i doing a mistake? please guide me

**Comment by HarshCasper** [comment]
Hello @agrima84 

As Developers, we often need to store secret information that we cannot risk exposing in public view. This includes, API Keys, Database Passwords and other configurations. Usually, we hardcode it, but the best practice includes, keeping it in a `.env` file so that it is not accidentally pushed on Git. 

While passing this Project, to our fellow Team-Mates, we often need to add a `.env.example` or `.env.sample` so that they understand on what are the environment variables that they need to store and satisfy. The other devs then can make a local copy of it and fill out the corresponding values.

But we all are humans, isn't it? We often forget to add this, and as Developers, we spend hours in finding the correct environment variables. So why not have a script that can parse the Codebase and find all environment variables and store them in a `.env.example` file? 

I was looking for this specific requirement in the Script. Let me know if you have any other questions.

**Comment by HarshCasper** [comment]
Closing this because of no updates!

**Pull request closed without merging**
