### PR TITLE
Solved #328 Launching Other Programs from Python

### LINKED ISSUE #328: Launching Other Programs from Python
# Description

Use python to run other programs on your computer like Calculator, etc.

## Language

- [x] Python

## Type of issue

- [x] Feature

### PR DESCRIPTION
**Pull request by sameersrivastava13**
# Description

Use python to run other programs on your computer like Calculator, etc.

Fixes #328 

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by sameersrivastava13** [comment]
@seema1711 @HarshCasper Please review.

**Comment by sameersrivastava13** [comment]
@seema1711 Please review i have updated the python directory readme file.

**Comment by HarshCasper** [comment]
Hello @sameersrivastava13 

The Script looks good to me. Is it possible to make use of Argument Parsers for the same, rather than directly taking in Input from the User? If you can make use of them, kindly update the Script otherwise I will merge this.

**Comment by sameersrivastava13** [comment]
> Hello @sameersrivastava13
> 
> The Script looks good to me. Is it possible to make use of Argument Parsers for the same, rather than directly taking in Input from the User? If you can make use of them, kindly update the Script otherwise I will merge this.

@HarshCasper yea we can use argument parser but i would suggest you to leave it as simple as it is and merge the script as this is the simplest script i tried making for better understanding. The issue can be solved in just one line but for better understanding i wrote the script like a menu driven program.

**Pull request merged**
