### PR TITLE
Color_picker

### LINKED ISSUE #819: Color Picker from Image/Video feed using Python
# Description

Pick the color from the pixel of the image which is mouse-clicked and print the RGB value of the color. Color Picker is one of the fundamental snippet widely used during Computer vision applications. Anyone who is interested to explore Computer Vision can take this issue.

## Language
- [X] Python

## Checklist:

- **Details on the Script**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Color Picker using Python | Pick a color on a mouse click from an image picture and display on console | Python, good-first-issue |  |

**Is your feature request related to a problem? Please describe.**: 
Color picker script is quite fascinating thing to implement as this has wide spectrum of use cases in video/image editing apps, extract color themes from the website layout, eye-dropper etc. 

**Describe the solution you'd like**:
When an image is clicked, trigger a callback which takes a pixel with [x,y,z]. All pixels are in RGB form and so the color can be extracted and printed in the console.

[This](https://www.youtube.com/watch?v=kdLM6AOd2vc&list=PLS1QulWo1RIa7D1O6skqDQ-JZ1GGHKK-K) is a good reference to learn basics of OpenCV apart from the official docs.

### PR DESCRIPTION
**Pull request by TITHI007**
# Description

These script use openCv to detect color of the coordinates we click on from the image. 
Fixes #819

## Type of change

_Please delete options that are not relevant._

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation Update

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by sohamsshah — CHANGES_REQUESTED** [review]
This looks a good implementation of the script @TITHI007 

There a few changes that you can address:
First I would encourage you to go through the [Style Guide](https://github.com/HarshCasper/Rotten-Scripts/blob/master/STYLE_GUIDELINES.md) and follow it throughout the codebase.

- Please add a `README.md` file that discusses about how to run this script and its output.
- Remove all the images/gifs and upload it directly to README from local or use `Imgur` for implementing this.
- Add comments in each User-Defined function that involves description of parameters and its functionality.
- Put everything in a function and remove all the global variables.
- Use `if __name__ == "__main__"` as a starting point of the code.
- Make a `requirements.txt` file that can be used to download dependencies for your script.

Please revert on these enhancements and your PR is ready-to-merge. Also, you can refer other scripts of python in the Repo for implementation. Feel free to ping me for any queries or doubts.
Thanks!

**Comment by TITHI007** [comment]
Thanks 
I will work on the changes and get back to it soon.

**Comment by sohamsshah** [comment]
@TITHI007 this PR affects multiple files which aren't related to your implementation. It would be better if you make a new branch from master, and commit the files again. Please resolve this :)

**Comment by vybhav72954** [comment]
Migrated to #899

**Pull request closed without merging**
