### PR TITLE
Added CSV-Splitter &  Updated Python/README.md

### LINKED ISSUE #506: Break Large CSVs into Smaller CSVs
# Description

While working on Audio Processing, there was a usual problem, my CSV (features of Audio) contained various features of various files, Copy Pasting was the only method that could be used to generate smaller CSVs.

`Pandas` or `csv` (python module) can sort this though, so how about a program that takes a CSV file as input, breaks it into smaller on, according to users preferences.

*The independence given to the user is the key.* Unlike other tools available online, I want users to have much more freedom.

## Language

- [x] Javascript
- [x] Python

## Type of issue

- [x] Feature

## Checklist:

- **For Feature**

| name            | about                                                  | labels  | assignees                                                      |
| ---- | ----------------------------------------- | ------ | -------------------------------------------------------------- |
| CSV-Breaker | Break a Large CSV into smaller one | feature, Python | @vybhav72954  |

**Is your feature request related to a problem? Please describe.**: I have explained above 😮 

**Describe the solution you'd like**: Read Description 😲 

**Additional context**: Give freedom to the user 🤗

### PR DESCRIPTION
**Pull request by vybhav72954**
# Description

A Python Script to Split `.csv` into smaller files according to user input.

Fixes #506 

_Also Updated Python/README.md_

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by HarshCasper** [comment]
LGTM! 

Thanks for updating the README. I was soon going to raise an Issue for that.

**Comment by HarshCasper** [comment]
give @vybhav72954 75 points

**Comment by vybhav72954** [comment]
@HarshCasper Just wondering it was `Hard` labeled. Not questioning your decision or something, wanted to clear a doubt

**Comment by HarshCasper** [comment]
give @vybhav72954 75 points

**Pull request merged**
