### PR TITLE
Inshorts News

### PR DESCRIPTION
**Pull request by virajmane**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixes #(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Hi @virajmane 

Thanks for sending us a PR! We appreciate your contributions. 

A few things before we merge your PR: 

- Please add an Issue Link. All Contributions are made via an Issue-PR workflow. We really appreciate if you can add an Issue that highlights your interest in having this script. 
- Please remove the Image File. We have removed all external files from the repository and we would appreciate if you can do so.
- Add proper DocStrings and Comments in your Python Code.
- Revert the changes in README. We don't need to update them as of now.

**Comment by virajmane** [comment]
If I make these changes, can I upload it under DWoC ?

**Comment by HarshCasper** [comment]
> If I make these changes, can I upload it under DWoC ?

DWoC is already over.

**Comment by HarshCasper** [comment]
Are you planning to work on it @virajmane ?

**Comment by virajmane** [comment]
Yeah

**Pull request closed without merging**
