### PR TITLE
Keylogger

### PR DESCRIPTION
**Pull request by avinashkranjan**
# Description
Fixes #(#126)

Using Python Language I've build this Keylogger which after a given interval of time .

### Added Functionalities : 🚀 

* Keylogging
* Can Save the keylogs in a file (you can change the local of file to wherever you want)
* Can print the keylogs after given interval of time (in the case 15 mins, you can change the time interval)
* Can mail you all the keylogs after given interval of time (in the case 15 mins, you can change the time interval).

#### Sample 
Screenshot (137)

## Type of change

- [ ✔] Bug fix (non-breaking change which fixes an issue)
- [ ✔] New feature (non-breaking change which adds functionality)
- [❌ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ✔] This change requires a documentation update

# Checklist:

- [✔ ] My code follows the style guidelines(Clean Code) of this project
- [✔ ] I have performed a self-review of my own code
- [ ✔] I have commented my code, particularly in hard-to-understand areas
- [✔ ] I have created a helpful and easy to understand README
- [❌ ] I have made corresponding changes to the documentation
- [❌ ] My changes generate no new warnings
- [✔ ] I have added tests/screenshots(If any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by HarshCasper** [comment]
Thanks for making a PR @avinashkranjan 

Please add brief documentation on how can someone use your Script. It would be ready to merge then

**Comment by avinashkranjan** [comment]
Sure @HarshCasper..I'll add  a ReadMe file to the folder which will contain all the instructions..

**Comment by avinashkranjan** [comment]
@HarshCasper Have a look added the documentation.

**Comment by HarshCasper** [comment]
Reviewed and Merged. Loved the implementation 🤗🙌

**Comment by HarshCasper** [comment]
@all-contributors please add @avinashkranjan for documentation

**Comment by HarshCasper** [comment]
@all-contributors please add @avinashkranjan for code

**Pull request merged**
