### PR TITLE
Strong Password Detection

### LINKED ISSUE #288: Strong password detection.
# Description

Make a Python Script that detects a strong password.

## Language

- [x] Python

## Type of issue

_Please delete options that are not relevant._

- [x] Feature

### PR DESCRIPTION
**Pull request by AdityaAshvin**
# Description

Added Script for Strong Password Detection

Fixes #288 

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by AdityaAshvin** [comment]
@seema1711 please review it.

**Comment by HarshCasper** [comment]
Add your Script in the README

**Comment by AdityaAshvin** [comment]
Done @HarshCasper  .

**Comment by HarshCasper** [comment]
Kindly resolve the Conflict

**Pull request closed without merging**
