### PR TITLE
Added 2 Text Summarization Techniques

### LINKED ISSUE #539: Create a Script to summarize Text
# Description

Create a Script to summarize Text. You can take a look at some SOTA Techniques to achieve this along with wrappers that make it really easy to summarize the Text. You can also try out your own algorithm for Text Summarization and to make it lightweight and-efficient at the same time.

## Language

- [X] Python

## Type of issue

_Please delete options that are not relevant._

- [X] Feature

### PR DESCRIPTION
**Pull request by vybhav72954**
# Description

Added 2 Text_Summarixation technique for comparison of the 2 most popular techniques using Deep Learning (pre-trained model)

Moreover made changes in `Python->README.md`
This also resolves changes in #702 #699 

Major - Fixes #539 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by vybhav72954** [comment]
@HarshCasper Can you please review my PRs, I need to delete my local copy of the Repo as I have way too many upstream and the `Head_ref` is messed up

**Review by HarshCasper — APPROVED** [review]
Wonderful work! Thanks 🚀

**Comment by vybhav72954** [comment]
@HarshCasper Can you rectify the labels too, in all of MY PR and issues, 

Script WOC
DevScript WOC
and MWOC

**Comment by HarshCasper** [comment]
> @HarshCasper Can you rectify the labels too, in all of MY PR and issues,
> 
> Script WOC
> DevScript WOC
> and MWOC

Can you drop all the links here? I will add them aptly.

**Pull request merged**
