### PR TITLE
JavaScript Readme under #issue-826

### LINKED ISSUE #826: New JavaScript README
As proposed in #796

We need a new JS template as well. The details have been mentioned in #796 already, using the guidelines provided n that issue, propose a new JS template.

### PR DESCRIPTION
**Pull request by SSHREYA71**
# Description
 Updated the documentation.
Added some more information.
Organized the scripts in ordered-list

Fixes #826

## Type of change

_Please delete options that are not relevant._

- [x] This change requires a documentation update
- [x] Documentation Update
- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by vybhav72954** [comment]
@SSHREYA71 I will review the PR by late-night, meanwhile, add a `Fixes #<issue_no>` in the body of PR.

Also, try editing the body of PR, you will enjoy it :P

**Comment by SSHREYA71** [comment]
> @SSHREYA71 I will review the PR by late-night, meanwhile, add a `Fixes #<issue_no>` in the body of PR.
> 
> Also, try editing the body of PR, you will enjoy it :P
Sure @vybhav72954 , On it.

**Review by vybhav72954 — APPROVED** [review]
LGTM

**Review by HarshCasper — CHANGES_REQUESTED** [review]
It doesn't look good to me. 

We have a numbered list that is poorly formatted. Don't get me wrong. I appreciate your efforts but it is not something we are looking for.

The tabular way of presentation was more appealing but updating it was a hectic task. Can you think of some other approach that we can possible follow? 

Also, use relative paths rather than direct links while adding links for scripts.

**Comment by SSHREYA71** [comment]
> It doesn't look good to me.
> 
> We have a numbered list that is poorly formatted. Don't get me wrong. I appreciate your efforts but it is not something we are looking for.
> 
> The tabular way of presentation was more appealing but updating it was a hectic task. Can you think of some other approach that we can possible follow?
> 
> Also, use relative paths rather than direct links while adding links for scripts.



> It doesn't look good to me.
> 
> We have a numbered list that is poorly formatted. Don't get me wrong. I appreciate your efforts but it is not something we are looking for.
> 
> The tabular way of presentation was more appealing but updating it was a hectic task. Can you think of some other approach that we can possible follow?
> 
> Also, use relative paths rather than direct links while adding links for scripts.

Sure, Let me think of a better way to do it. And I actually don't know how to use relative paths, could you please brief me a little more.

**Comment by SSHREYA71** [comment]
> It doesn't look good to me.
> 
> We have a numbered list that is poorly formatted. Don't get me wrong. I appreciate your efforts but it is not something we are looking for.
> 
> The tabular way of presentation was more appealing but updating it was a hectic task. Can you think of some other approach that we can possible follow?
> 
> Also, use relative paths rather than direct links while adding links for scripts.

@HarshCasper I have tried formatting the list properly and also added relative paths for the script as you asked. But I couldn't think of any other way to write the scripts other than in list form or tabular form. If you have something in mind please tell me, I will implement it well.

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Still not very satisfied with it. Can we go back to the tabular format and ensure that the alphabetical format is no longer needed? 

(EDIT) 

New suggestion. We can follow this: https://github.com/HarshCasper/Rotten-Scripts/pull/854/files

**Comment by SSHREYA71** [comment]
> Still not very satisfied with it. Can we go back to the tabular format and ensure that the alphabetical format is no longer needed?
> 
> (EDIT)
> 
> New suggestion. We can follow this: https://github.com/HarshCasper/Rotten-Scripts/pull/854/files

So I only list the scripts without their authors? Okay on it

**Comment by SSHREYA71** [comment]
@HarshCasper  Please look into the updates I made.

**Review by HarshCasper — APPROVED** [review]

**Comment by HarshCasper** [comment]
I made some changes myself. Thanks :sparkles:

**Pull request merged**
