### PR TITLE
Adding extra feature

### LINKED ISSUE #841: Word cloud generator using python
needed **This template is strictly for requesting New Scripts, if you want a new feature (automating this Repo,**
**a change in structure) in the Repo,** 
**or you want to report a Bug. There are other templates which you should follow**

# Description

 I want to add python scripts for generating word cloud which is a famous data visualization technique used.

## Language

- [ ] Bash
- [ ] Go
- [ ] Javascript
- [ ] Powershell
- [x] Python
- [ ] Other (Please specify)

## Checklist:

- **Details on the Script**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Wordcloud_Generator | Adding new feature | GSSOC21 | @Rupa-421 |

**Is your feature request related to a problem? Please describe.**: No it's not about fixing any bug.It's just a new additional feature that is cool to implement.

**Describe the solution you'd like**: I'm going to use pandas to read the data needed. Then I will use word cloud module to generate word cloud. Then I will display output using matplotlib.

**Additional context**: Word clouds are widely used for analyzing data from social network websites.

### PR DESCRIPTION
**Pull request by Rupa-421**
# Description

By introducing this feature we can generate word cloud by input of csv files also.

Fixes #841 

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [x] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by vybhav72954** [comment]
@Rupa-421 Are you new to GitHub? Or by mistake, you have made 2 PRs for the same issue?
Reference: #911

**Comment by Rupa-421** [comment]
No I forgot to update readme 😂 and after I saw about documentation in pr description and then I changed readme while my one pr is in progress 😅.So that messy thing happened

**Comment by vybhav72954** [comment]
> No I forgot to update readme 😂 and after I saw about documentation in pr description and then I changed readme while my one pr is in progress 😅.So that messy thing happened

Never mind XD. Please close that PR and update the README in this very branch

**Review by HarshCasper — APPROVED** [review]

**Comment by vybhav72954** [comment]
Oh wait it got merged XD
@Rupa-421 Thank you for updating a existing code

**Pull request merged**
