### PR TITLE
Add Khan Academy Downloader bash script

### LINKED ISSUE #807: Script to download Khan Academy Videos
# Description

Create a Script to download videos from Khan Academy. The Script should be available with some default options like: 

- Downloading a Course by passing ahead the URL 
- Search the courses interactively and downloading them ahead
- Downloading all the courses all together 

You are free to have your own customization as part of it and come up with your own unique ideas.

## Language
- [X] Go
- [X] Javascript
- [X] Python

## Checklist:

- **Details on the Script**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Khan Academy Downloader | Download Khan Academy Videos | Up-for-Grab, Hard, good first issue | |

### PR DESCRIPTION
**Pull request by pganguli**
# Description

Added a bash script to download videos from Khan Academy using youtube-dl.

Closes #807

## Type of change

- [X] New feature (non-breaking change which adds functionality)

# Checklist:

- [X] My code follows the style guidelines(Clean Code) of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by pganguli** [comment]
Debugging the regex patterns that scrape the titles and urls from the official website took a lot of work, but it was fun to write :)
Kindly review the files and let me know if anything can be improved. 
@vybhav72954 
@HarshCasper

**Comment by vybhav72954** [comment]
@pganguli Looks solid to me but i will implement it once. I will surely provide my review today

**Comment by pganguli** [comment]
> @pganguli Looks solid to me but i will implement it once. I will surely provide my review today

Any updates on this? Thanks.

**Comment by HarshCasper** [comment]
@pganguli I would make a review myself by tomorrow. Thanks for your patience on this!

**Comment by seema1711** [comment]
This code wasn't working for me first, I had to do these steps, you may want to include these in the README file too:
In order to run the script, you have to run these commands. I used Fedora 32.
```
$ wget http://rpmfind.net/linux/RPM/mageia/cauldron/aarch64/media/core/release/perl-HTML-Parser-3.760.0-1.mga9.aarch64.html

$ sudo dnf install http://rpmfind.net/linux/mageia/distrib/cauldron/aarch64/media/core/release/perl-HTML-Parser-3.760.0-1.mga9.aarch64.rpm

$ sudo dnf install perl-HTML-Parser
```
After this, the script is working completely fine! Good work.

**Comment by pganguli** [comment]
> This code wasn't working for me first, I had to do these steps, you may want to include these in the README file too:
> In order to run the script, you have to run these commands. I used Fedora 32.
> 
> ```
> $ wget http://rpmfind.net/linux/RPM/mageia/cauldron/aarch64/media/core/release/perl-HTML-Parser-3.760.0-1.mga9.aarch64.html
> 
> $ sudo dnf install http://rpmfind.net/linux/mageia/distrib/cauldron/aarch64/media/core/release/perl-HTML-Parser-3.760.0-1.mga9.aarch64.rpm
> 
> $ sudo dnf install perl-HTML-Parser
> ```
> 
> After this, the script is working completely fine! Good work.

Ah, I'm on Fedora 33 myself, and I suppose some package that I had installed already pulled in perl-HTML-parser as a dependency, which is why I didn't have to install it.
I can add the commands to the README.md, but then that'd be specific to RHEL based distros (Also, is the first command necessary? The last two should suffice). Maybe I can just mention that the HTML parser module for perl needs to be present?

**Comment by seema1711** [comment]
> > This code wasn't working for me first, I had to do these steps, you may want to include these in the README file too:
> > In order to run the script, you have to run these commands. I used Fedora 32.
> > ```
> > $ wget http://rpmfind.net/linux/RPM/mageia/cauldron/aarch64/media/core/release/perl-HTML-Parser-3.760.0-1.mga9.aarch64.html
> > 
> > $ sudo dnf install http://rpmfind.net/linux/mageia/distrib/cauldron/aarch64/media/core/release/perl-HTML-Parser-3.760.0-1.mga9.aarch64.rpm
> > 
> > $ sudo dnf install perl-HTML-Parser
> > ```
> > 
> > 
> > After this, the script is working completely fine! Good work.
> 
> Ah, I'm on Fedora 33 myself, and I suppose some package that I had installed already pulled in perl-HTML-parser as a dependency, which is why I didn't have to install it.
> I can add the commands to the README.md, but then that'd be specific to RHEL based distros (Also, is the first command necessary? The last two should suffice). Maybe I can just mention that the HTML parser module for perl needs to be present?

It's better now, but to improve the README file maybe you can add the commands on how to install the modules, it will be a better option, and users won't have to Google it.

**Comment by pganguli** [comment]
Kindly let me know if you think any further improvements are required.

**Comment by seema1711** [comment]
Perfect! Kudos @pganguli. 🚀

**Review by HarshCasper — APPROVED** [review]

**Pull request merged**
