### PR TITLE
Fixes Issue #735 - Video to Images at required FPS

### PR DESCRIPTION
**Pull request by RutvikJ77**
# Description

Video to Image Script at required Frame rate per second. OpenCV is required for the script to run.

Fixes #(issue_no)

Replace `735` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Please make the README updates. Rest looks good to go 👍

**Review by RutvikJ77 — COMMENTED** [review]
I corrected a few mistakes with the video file names and the python filename. I did not find any such changes, can you suggest me if there are any other? Additionally, I am confused as to why the readme is not passing through the check spelling bot.

**Comment by HarshCasper** [comment]
> I corrected a few mistakes with the video file names and the python filename. I did not find any such changes, can you suggest me if there are any other? Additionally, I am confused as to why the readme is not passing through the check spelling bot.

Please ignore that. In the meantime, please edit the Python README which contains all the details of the Scripts available in a specific language.

**Comment by RutvikJ77** [comment]
> > I corrected a few mistakes with the video file names and the python filename. I did not find any such changes, can you suggest me if there are any other? Additionally, I am confused as to why the readme is not passing through the check spelling bot.
> 
> Please ignore that. In the meantime, please edit the Python README which contains all the details of the Scripts available in a specific language.

Got It, due to some weird reason the click here link is not showing up, so I am thinking to close this pull request and create a fresh one with a proper folder name.

**Pull request closed without merging**
