### PR TITLE
Image Edges Detector

### LINKED ISSUE #711: Add a python script to detect the edges of the image
I will add a python script that will act as canny edge detector and detect the edges of the images. I will use opencv for detecting the edges. I am a participant in DWOC and want to contribute. @HarshCasper Kindly, add the labels and please assign this issue to me.

### PR DESCRIPTION
**Pull request by Dhanush2612**
Python script to detect the edges of the image.
Readme included

Fixes #711

### CODE REVIEW

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Please add a corresponding Issue so that we can review.

**Comment by Dhanush2612** [comment]
@HarshCasper 
What is the issue with this PR?

**Comment by vybhav72954** [comment]
> @HarshCasper
> What is the issue with this PR?

I don't know why you removed completely deleted the PR template. I will link the issue myself.

**Comment by Dhanush2612** [comment]
@vybhav72954 
I have made changes as per the requirements.
Changed the loops, definitions, etc.
It works

**Review by HarshCasper — CHANGES_REQUESTED** [review]
You have pushed the directory on root. 

I will put this PR under `spam`. Please follow the standard conventions while making PRs

**Comment by Dhanush2612** [comment]
@vybhav72954 
I am sorry. Shall I create a new PR?

**Comment by vybhav72954** [comment]
PLease make a New PR and make sure that you commit files in `Python` directory and please go through the guidelines once!

**Pull request closed without merging**
