### PR TITLE
Changed PyLint Action

### LINKED ISSUE #674: Make PyLint action more strict
**Describe the bug**
Recently I noticed, that the moderators have started paying more emphasis on advanced styling techniques like `docstrings` and `shebang`, the current PyLint Action, made by me is deliberately more tolerant (I thought that we were ignoring advanced styling), considering maintainers are all in for Good staying, the PyLint action needs to be updated.

**To Reproduce**
1. Go to Any new PR
2. Check if Docstrongs, shebang, EOF are properly formatted or not
3. If not, see the PyLint Action Result
4. No error displayed

**Expected behavior**
Although this is expected, cause the Action was made to be tolerant, it's time we get rid of that, and make it more strict.

### PR DESCRIPTION
**Pull request by vybhav72954**
# Description

Configured the PyLint action so that it is more strict than before. Still, it will ignore some styling errors like the number of attributes, methods, etc.

But will no longer ignore redundant names, missing docstrings etc

Fixes #674 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by vybhav72954** [comment]
For now, this code will run on the whole codebase as a test run.

I will update this in a later commit.

**Comment by vybhav72954** [comment]
@HarshCasper You can now see the action dashboard, not only the action is way more strict, but the results are better formatted as well

**Comment by vybhav72954** [comment]
@HarshCasper Action now runs only on the new files

**Comment by HarshCasper** [comment]
HI @vybhav72954 

Github Actions has automatically generated some warnings and errors for the Action. Can you take a look and rectify them?

**Comment by vybhav72954** [comment]
Can you check #672 @HarshCasper

**Comment by HarshCasper** [comment]
Is it still under work @vybhav72954 ?

**Comment by vybhav72954** [comment]
> Is it still under work @vybhav72954 ?

The PyLint actions definitely working properly, for rest of the actions, I believe in discussion #672, we decided first to create guidelines, then any further edits, so yes this is up for review since verybeginning

**Review by HarshCasper — APPROVED** [review]

**Pull request merged**
