### PR TITLE
Added Github_Unfollowers with all changes requested

### LINKED ISSUE #732: Find Unfollowers on Github
## Description 

There are a lot of people who follow people and unfollow them as well, later. While we don't exactly know, under what circumstances is the `Unfollow` button clicked, but we for sure, don't know who unfollowed us. 

Build a Script/CLI that can track the Usernames who unfollowed you recently on Github. 

## Languages 

- Python
- Javascript
- Golang
- BASH

### PR DESCRIPTION
**Pull request by vismitap**
Fixed #732

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixes #732 

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by HarshCasper — APPROVED** [review]
LGTM! 

Thanks 🎉

**Comment by HarshCasper** [comment]
@all-contributors bot please add @vismitap for code

**Comment by HarshCasper** [comment]
@all-contributors bot please add @vismitap for documentation

**Comment by vismitap** [comment]
Hey! I am participating in SWoC and MWoC could you please add those labels also? 😅🙏

**Comment by HarshCasper** [comment]
> Hey! I am participating in SWoC and MWoC could you please add those labels also? 😅🙏

I have added the label but the leaderboard does not seem to automatically pick it up. I have asked the admin to update it manually so you can see the updated results in sometime.

**Pull request merged**
