### PR TITLE
Updated the Test-Typing-Speed

### PR DESCRIPTION
**Pull request by avishmehta68710**

### CODE REVIEW

**Comment by HarshCasper** [comment]
Can you reference the Issue you were working on?

**Comment by avishmehta68710** [comment]
the code when executed gave the errors. so i have just fixed those errors and updated the code to be error free.

**Comment by HarshCasper** [comment]
Please create an Issue @avishmehta68710 so that it can be logged.

Also are you participating as part of Contributor's Hack 2020?

**Comment by avishmehta68710** [comment]
ok i will create the issue
i was bit late to fill the form so i am not participating the contributors hack 2020

**Comment by HarshCasper** [comment]
Thanks for making the changes. Really appreciate your contribution in Open-Source

**Comment by HarshCasper** [comment]
@all-contributors please add @avishmehta68710 for code

**Pull request merged**
