### PR TITLE
Add Flask_Directory_Initiator

### LINKED ISSUE #425: Python Script to initialize a Flask Folder Structure
# Description

Create a Python Script that can be used to initialize a Flask Folder Structure. Your Script should take arguments from the User on what should be the name of the Project, the Folder Location and create a Virtual Environment for the same. The Folder Structure for majority of the Flask Projects looks something like this: 
```
~/FlaskApp
    |-- run.py
    |-- config.py
    |__ /env             # Virtual Environment
    |__ /app             # Our Application Module
         |-- __init__.py
         |-- /module_one
             |-- __init__.py
             |-- controllers.py
             |-- models.py                
         |__ /templates
             |__ /module_one
                 |-- hello.html
         |__ /static
         |__ ..
         |__ .
    |__ ..
    |__ .

```

## Language

- [X] Python

## Type of issue

_Please delete options that are not relevant._

- [X] Feature

### PR DESCRIPTION
**Pull request by DevChoganwala**
# Description

Added a python script to initiate flask directory and setup a virtual environment within that directory. Includes the script file and a readme with steps to run the script.
Modules Used : `virtualenv`, `os`, `sys`.

Fixes #425 

## Type of change

_Please delete options that are not relevant._

- [X] New feature (non-breaking change which adds functionality)

# Checklist:

- [X] My code follows the style guidelines(Clean Code) of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by HarshCasper** [comment]
Hello @DevChoganwala 

Thanks for making this PR. Can you possibly introduce some steps on how to run this Script. I tried running the same on my Local Machine and it threw up an ugly error: `AttributeError: module 'virtualenv' has no attribute 'cli_run'`

**Comment by DevChoganwala** [comment]
@HarshCasper The function `cli_run` was added to the module `virtualenv` after V20 so the error may have appeared due to an older version of the module. Should I update the README to include the version of modules I am running?

**Comment by vybhav72954** [comment]
> @HarshCasper The function `cli_run` was added to the module `virtualenv` after V20 so the error may have appeared due to an older version of the module. Should I update the README to include the version of modules I am running?
I Suggest making a requirement.txt file using ```pip freeze > requirement.txt``` It will specify all the specific versions and will help others who are setting up on local.

**Comment by DevChoganwala** [comment]
> > @HarshCasper The function `cli_run` was added to the module `virtualenv` after V20 so the error may have appeared due to an older version of the module. Should I update the README to include the version of modules I am running?
> > I Suggest making a requirement.txt file using `pip freeze > requirement.txt` It will specify all the specific versions and will help others who are setting up on local.

@vybhav72954 Thank you for the suggestion. I will make a requirement.txt and update the PR.

**Comment by seema1711** [comment]
@HarshCasper I have reviewed the files. All good.

**Comment by HarshCasper** [comment]
Thanks a lot for the review @seema1711 

Great Work @DevChoganwala

**Comment by HarshCasper** [comment]
give @DevChoganwala 50 points

**Comment by HarshCasper** [comment]
give @DevChoganwala 75 points

**Pull request merged**
