### PR TITLE
Github Action to label issues as "Hacktoberfest"

### PR DESCRIPTION
**Pull request by HariAcidReign**
# Description

The Action adds the "Hacktoberfest" tag on every newly opened issue when the time frame is between the 1st and 31st of October. I put the value as empty space for the key Hacktoberfest, just to accommodate all issues to get this label.
This is my first time contributing to this repo. So if there is something wrong/to be done, let me know. 

Fixes #(#382 )

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by HarshCasper** [comment]
@seema1711 Can you possibly check the Action if the action would work fine as desired?

**Comment by seema1711** [comment]
Sure.

**Comment by seema1711** [comment]
GitHub action is not working. It doesn't add a label to the issues.

**Comment by HariAcidReign** [comment]
Hi @seema1711 , can you check the code and tell me why it isn't working? This is my first Action, so if you can let me know where I'm wrong, I can rectify it ASAP 😄

**Comment by seema1711** [comment]
It's running without any error, but now labeling "Hacktoberfest". Did you check it yourself?

**Comment by HariAcidReign** [comment]
Well sadly, I don't have the option of creating an issue on my forked repo to check if the action I created is working. I made that using intuition. Is there a work-around that I am missing? Does the code look fine?

**Comment by HarshCasper** [comment]
@HariAcidReign You can try out this [tool](https://github.com/nektos/act) to test your Github Actions locally

**Comment by HariAcidReign** [comment]
Hey @HarshCasper , the tool you mentioned above wasn't working in my machine for some reason, so I did a trial run on one of my repos, and the action is running properly. Can you please check the code again and tell me if it looks right to you?

**Comment by vybhav72954** [comment]
@HariAcidReign I can help you if you want.

**Comment by vybhav72954** [comment]
> @HariAcidReign I can help you if you want.

Can you generate Logs of your action? Go to the action in the navigation bar after you have launched a PR, or pushed something (as applicable to your Action) there you will see workflows, you can then generate a set of Log FIles (Use [Google](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/using-workflow-run-logs#:~:text=Searching%20logs,-You%20can%20search&text=perform%20these%20steps.-,On%20GitHub%2C%20navigate%20to%20the%20main%20page%20of%20the%20repository,run%20you%20want%20to%20see.)). Attach those log files here, am pretty sure we can do this together

**Pull request closed without merging**
