### PR TITLE
Added: banner image for repo #398

### LINKED ISSUE #398: Make a Banner Image for the Repository
# Description

Make a Banner Image for the Repository. The Banner Image can be simply the title of this Project with an awe-striking background. This Issue can be assigned to any number of participants but only one would be accepted as the Main Banner.

You need to submit: 

- The Raw File of the Banner 
- A JPEG/PNG File of the Output

## Tools

- [X] Adobe XD
- [X] Figma 
- [X] Photoshop

## Type of issue

_Please delete options that are not relevant._

- [X] Feature
- [ ] Bug

### PR DESCRIPTION
**Pull request by SuvamPrasd**
# Description
Designed Rotten Scripts banner image for the repo using Figma web software tools. The design consists of striking thunder night landscape background, repository title(font-family - Architects Daughter), designed unique carrot icons.

Fixes #398 

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by seema1711** [comment]
It is good but doesn't suit the project.

**Comment by srimani-programmer** [comment]
@SuvamPrasd  Try to implement a suitable one for the project. that doesn't fit the project.

**Review by srimani-programmer — CHANGES_REQUESTED** [review]
Requesting to develop the icon that suits the project.

**Comment by HarshCasper** [comment]
@SuvamPrasd Are you working on the same?

**Comment by SuvamPrasd** [comment]
Sorry, @HarshCasper can please assign this design to someone else.

**Pull request closed without merging**
