### PR TITLE
 Verbose mode added and Improve output formatting #923

### LINKED ISSUE #923: Add verbose mode for PR_workflow script
# Description

Update PR_workflow script. As you might have noticed, there is option for verbose mode but the feature is missing 
i want to work on this and want to add verbose mode in it.

@vybhav72954 
@HarshCasper 

| name            | problem/motivation                                                  | possible solution  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| verbose mode | missing verbose mode | by using graphQL query | @rahulraikwar00  |

### PR DESCRIPTION
**Pull request by rahulraikwar00**
# Description

Update PR_workflow script. As you might have noticed, there is option for verbose mode but the feature is missing
i want to work on this and want to add verbose mode in it.

Fixes #923 
@HarshCasper 

## Type of change

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by rahulraikwar00** [comment]
@vybhav72954 @HarshCasper   could you please review it ?

**Review by vybhav72954 — CHANGES_REQUESTED** [review]
@rahulraikwar00 Considering we are about to properly finalize this project, let's enforce PEP-8 Guidelines as well shall we?

Do you know how to use autopep-8? In case you don't, either ook it up on google, or here is a simple [walkthrough](https://dev.to/vybhav/beginners-guide-to-auto-formatting-1hpp) for you.

Use aggressive,  formatting as well.

**Comment by vybhav72954** [comment]
I checked the pylint score as well, the average was 8. Maybe we can increase it using the above-mentioned tools as well.

**Comment by rahulraikwar00** [comment]
> @rahulraikwar00 Considering we are about to properly finalize this project, let's enforce PEP-8 Guidelines as well shall we?
> 
> Do you know how to use autopep-8? In case you don't, either ook it up on google, or here is a simple [walkthrough](https://dev.to/vybhav/beginners-guide-to-auto-formatting-1hpp) for you.
> 
> Use aggressive,  formatting as well.

Ya sure , I'll definitely go through it.👍🏻

**Comment by rahulraikwar00** [comment]
@vybhav72954  now pylint score is arround 9.07 which is fairly good  i guess ! what do you think?

**Comment by rahulraikwar00** [comment]
@vybhav72954 now could you please review it?

**Comment by rahulraikwar00** [comment]
@HarshCasper @vybhav72954  can you please have a look at this?

**Comment by vybhav72954** [comment]
> @HarshCasper @vybhav72954 can you please have a look at this?

Hey sorry, I got a bit busy, @HarshCasper LGTM

**Review by vybhav72954 — APPROVED** [review]

**Review by HarshCasper — APPROVED** [review]

**Pull request merged**
