### PR TITLE
Random password generator

### LINKED ISSUE #299: Random password generator.
# Description

Write a Python script to generate a random password.

## Language

- [x] Python

## Type of issue

- [x] Feature

### PR DESCRIPTION
**Pull request by Guilherme-Vasconcelos**
# Description

Added a script for generating a random password and added it to the list of scripts.

Fixes #299 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by seema1711** [comment]
In the readme file, the images don't have the right URL.

**Comment by Guilherme-Vasconcelos** [comment]
Hello! Thank you for the feedback, I made a few changes

**Comment by HarshCasper** [comment]
Kindly resolve the conflicts

**Comment by seema1711** [comment]
image
We do like this.

**Comment by Guilherme-Vasconcelos** [comment]
Hello! I fixed the conflict, everything seems to be okay now @HarshCasper

**Comment by seema1711** [comment]
Right-click on the image, and copy the image address and paste in the readme file.

**Comment by Guilherme-Vasconcelos** [comment]
Sorry, the images seem to display correctly to me. Is it a project standard to use the url in the readme?

**Comment by seema1711** [comment]
image
It's like this. 
Right-click on the image and copy-paster the image address.
Like this.
image

**Pull request merged**
