### PR TITLE
Blog Image Finder #336

### LINKED ISSUE #336: Make a customized blog header.
# Description

When writing technical blogs, we need some images to tell about the blog, and it's hard to find relatable pictures sometimes, and they are sometimes copyrighted. So, make a customized program that can generate images for your blogs.

## Language

- [x] Javascript
- [x] Python

## Type of issue

- [x] Feature

### PR DESCRIPTION
**Pull request by gupta-piyush19**
# Description

This script generates images for blogs of any genre. Just give the category/genre name you want

Fixes #336 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update
- [x] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by gupta-piyush19** [comment]
@HarshCasper @seema1711 Kindly check this PR and give your valuable suggestions, and also I've one another pending PR that needs to be merged.
I also want to address one issue, my last PR is not merged that's why this PR is now comprising changes of two PR that needs to be calculated individually, please do take care of this as well.

**Comment by seema1711** [comment]
I don't know much about JS. @HarshCasper can you help?

**Comment by gupta-piyush19** [comment]
> 
> 
> I don't know much about JS. @HarshCasper can you help?

you may check the screenshot and tell me if the script I have written is serving the purpose of the issue or not.

**Comment by gupta-piyush19** [comment]
@HarshCasper kindly review this PR

**Comment by gupta-piyush19** [comment]
@HarshCasper Please check this PR.

**Comment by HarshCasper** [comment]
@gupta-piyush19 You seem to have pushed more than one scripts in one single PR. Kindly remove your encoding script and it will be ready to review.

**Comment by gupta-piyush19** [comment]
@HarshCasper I have my 2 PR pending to get merged, the older one was of encoding and the new one is this image finder, but because my first PR is not merged yet, the second one is having changes of both the PR, so you can merge them individually or just merge this one and I'll close the encoding script PR. please tell me the way you want the PRs.

**Comment by HarshCasper** [comment]
I have merged your Base 64 Encoding/Decoding Script. You can remove that Script from this PR now

**Comment by gupta-piyush19** [comment]
@HarshCasper I've deleted Base64 Script from this PR, but now it is showing merge conflict due to that deleted script, but this will not generate any further error, you may merge this PR now or I will make a new PR for the same.

**Pull request closed without merging**
