### PR TITLE
Remove images from repository

### LINKED ISSUE #677: Remove all Images from the Repository
## Description 

Remove all Images from the Repository. If you would have noticed, while `git clone`, that this repository is kinda HUGE. And if I look back at the reasons, it might due to some stupid requirements that I put over it in the initial stages. 

One of them included having Images and GIFs to show the Code Preview or the Script demonstration. As more Scripts were added, this became huge and redundant for us in the longer run. 

This Issue would require to remove all images from the Project and replace them with Imgur Links. Imgur has this nice interface [here](https://imgur.com/upload) to upload Images and then reference them on Markdown, for JPEG/PNG/GIF.

### PR DESCRIPTION
**Pull request by Zircoz**
# Description

All images have been replaced by uploading them to imgur.com and/or snipboard.io 

Fixes #677 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have performed a self-review of my own work
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by Zircoz** [comment]
Important Notes:

- Scripts in which images and/or assets are essential since they are editing/encrypting them/or are not touched (wherever the output image can be recreated by just running the script once, output images are deleted (not from readme))
- In some Readme files, contributors have added screenshot and then hyperlinked their blog's pictures/their own fork's image file/their image file uploaded somewhere (imgur, aws etc). In such cases, I gave deleted their image files and left readme's as they were (they are working).
- In case 1's solution, perhaps we can as the original contributors to upload their videos/image datasets on GDrive or something similar (?)
- Snipboard has been used because I hit imgur's hourly request quota of free account, lol.

**Comment by Zircoz** [comment]
About the failing checks :| 
- I haven't edited the code, so probably linters were already failing.
- Spell Check is doing too many false positives on names and short forms (link "repo").
- Someone's Linkedin links aren't working perfectly

**Comment by vybhav72954** [comment]
> About the failing checks :| 
> - I haven't edited the code, so probably linters were already failing.
> - Spell Check is doing too many false positives on names and short forms (like "repo").
> - Someone's Linkedin links aren't working perfectly

I am working on the linters @HarshCasper i checked the Linters for this PR, There are no problem ao you can safely ignore them.

@Zircoz let's wait for Harsh to review, this looks good and your logic in the previous comment seems correct to me

**Comment by HarshCasper** [comment]
Hi @Zircoz 

First things first: Thanks for this PR! 

It takes a lot of patience to put ahead some manual work and make such a large PR. I will start reviewing the PR now and will make sure to merge it as quick as possible.

**Comment by Zircoz** [comment]
Heyy @HarshCasper & @vybhav72954 
I am glad I got to do this and thanks for your patience (since I technically took 25+ days lol).
I do realize that this task is actually very tedious and I plan to make 2 scripts for automating (most) of it. I will do the necessarily for that contribution when I am sure that I have enough time to work on them. :D Thanks!

**Review by HarshCasper — APPROVED** [review]

**Comment by HarshCasper** [comment]
Thanks a lot!

**Comment by vybhav72954** [comment]
Wowwwwwww, thank you so much @Zircoz

**Pull request merged**
