### PR TITLE
Implementation of Google News Scrapper

### LINKED ISSUE #449: Google News Scrapper
# Description
Developing a Script in python to scrape the news articles from google news.
## Language

- [X] Python

## Type of issue

- [X] Feature

I would like to implement this script as part of Hacktoberfest.

### PR DESCRIPTION
**Pull request by srimani-programmer**
# Description

Implemented the Google News Scrapper using Python.

Fixes #449 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:
- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

@HarshCasper please review my PR

### CODE REVIEW

**Comment by HarshCasper** [comment]
LGTM!

**Comment by srimani-programmer** [comment]
@seema1711 please review my PR once.

**Comment by seema1711** [comment]
Ready to get merged. Good work @srimani-programmer

**Comment by srimani-programmer** [comment]
@HarshCasper The review is completed for this PR. can you please merge it.!

**Pull request merged**
