### PR TITLE
Find tweet

### LINKED ISSUE #300: Tweet search.
# Description

Sometimes we are searching for a particular tweet on the accounts you follow, and you just SCROLL down but don't get that tweet. Let this Python script help you.

## Language

- [x] Python

## Type of issue

- [x] Feature

### PR DESCRIPTION
**Pull request by basketcase03**
# Description

Added python script to search for a given tweet in all of the user's following. Makes use of Tweepy library.

Fixes #300 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by seema1711** [comment]
Can you update the main README file, and put the correct links for the code in your readme file.

**Comment by basketcase03** [comment]
I've corrected it now. If it needs any more corrections do let me know!

**Comment by seema1711** [comment]
https://raw.githubusercontent.com/HarshCasper/Rotten-Scripts/9fba0edecfa37b981bc78d3f8fb394ca0cfad54b/Python/Find_Tweet/Result.jpg

This will be the URL for the image. Right click on the image, and copy the image address.

**Comment by basketcase03** [comment]
I'm sorry, I thought it was the twitter link that needed correction. I've corrected the image links.

**Comment by seema1711** [comment]
Review did. Thank you for your contribution.

**Comment by seema1711** [comment]
You haven't updated the main readme file. Please do that.

**Comment by basketcase03** [comment]
I'm sorry, the main readme as in? The python directory README?

**Comment by seema1711** [comment]
Yes

**Comment by basketcase03** [comment]
Wouldn't that be done after the merge? Because I do not have the link to the file yet. Should I put in what the link will be after the merge?

**Comment by seema1711** [comment]
No.

**Comment by basketcase03** [comment]
I've changed the Readme. Please check

**Comment by seema1711** [comment]
Kindly resolve the issues.

**Comment by basketcase03** [comment]
Done.

**Pull request merged**
