### PR TITLE
Conflicts

### LINKED ISSUE #718: Irregular Directory Names
This is in relation to #688 

While looking for dead code, I found multiple Repos with names that don't align with the naming convention.

I think we should change them for the sake of aesthetics.
Considering we have a new `README` as well now, one will have to change the Links in it as well.

@HarshCasper If you think that we need to rectify them, you can assign me or anyone else for that matter, would be great if this is fixed ASAP as the last thing we need is merge conflicts because the name of directories has changed.

### PR DESCRIPTION
**Pull request by vybhav72954**
# Description

Because of the multiple merge conflicts, I was forced to make a new PR.

This original PR - #760, the changes were accepted but because i deleted the local branch in my own local fork, i had to make a new PR.

Fixes #718

### CODE REVIEW

**Review by HarshCasper — APPROVED** [review]

**Comment by HarshCasper** [comment]
Hello @sohamsshah 

Can you please have a look at it once?

**Review by sohamsshah — CHANGES_REQUESTED** [review]
Hi @vybhav72954, first of all thanks for taking time for refactoring the file names. Most of the work seems good to me. Though I found some `directories` which were missed out. Can you address these?

Directory Names that can be changed:
* Go/port-scanner-go
* Python/chromedino_script
* Python/cryptocurrency_converter

Also, as an enhancement; 
All Readme files must have `README.md` Name instead of `readme.md` or 'Readme.md` so as to have consistent naming pattern.

Changes required at:

In Go
* Go/porter-scanner-go/Readme.md 

In Javascript:
* Automate_Tinder
* Follow_Instagram
* HTML_To_Markdown
* Instagram_Like
* Who_Don't_Follow_You

In Python also some directories do have bad naming for README.md files. Though IMO, since the directory size is too large, can be ignored for the moment OR a simple script that can `rename` all the bad Readme files can be also a good way to tackle this.

@HarshCasper Should we have some tests that checks the naming convention for these as well? Let me know your opinions upon this.

**Comment by vybhav72954** [comment]
@sohamsshah Thanks for the Update, I actually never checked the JS and GO directory which is a shortcoming on my part.

I believe a separate script would be a good idea for `README` and I can make a separate issue for that, the reason I suggest we don't do any changes in the READMEs as of now because I believe that for the to be launched static website, we would have to change READMEs anyway (I would be doing the same). I will change the names of the files then and there only.

A github check for enforcing a naming convention is a good idea that can be explored in the future though.

**Comment by vybhav72954** [comment]
The files in the Python DIctionary are newly added scripts, that's why I failed to correct them in my previous commits.

**Review by vybhav72954 — COMMENTED** [review]
I have made the required changes apart from `README` the reason for which I have explained above already.

**Review by sohamsshah — APPROVED** [review]
Sounds good to me. Thanks @vybhav72954 !

**Pull request merged**
