### PR TITLE
Script to scrap all the E-Mails in a Webpage.

### PR DESCRIPTION
**Pull request by amandp13**
# Description

A Script to scrape all the Emails present on the webpage using Python.

## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

# Screenshot 

webpage-email-scrape py - Email_Scrape_From_Webpage - Visual Studio Code

### CODE REVIEW

**Comment by HarshCasper** [comment]
Project Codebase has been optimized and modified right now. Please pull the new changes to your Fork and make a fresh PR.

**Comment by amandp13** [comment]
I can't find what is modified.

**Comment by amandp13** [comment]
@HarshCasper Please Review #257

**Comment by amandp13** [comment]
@HarshCasper Look into this please.

**Comment by HarshCasper** [comment]
@amandp13 Can you ping me up on Slack? You need to pull all changes to your Fork and go into the Python Sub-Directory and then add your Script with Documentation up there.

**Comment by amandp13** [comment]
@HarshCasper Share your slack id

**Comment by amandp13** [comment]
@HarshCasper Created new PR, Please review #349

**Pull request closed without merging**
