### PR TITLE
Added YAML, MarkDown Lint, Spell Check, Link Check 

### LINKED ISSUE #401: Check a valid YAML file.
# Description

We often use YAML, but there are times it can confusing in terms of the wrong indentation, so this script will help to validate the YAML file.

## Language

- [x] Python

## Type of issue

- [x] Feature

### LINKED ISSUE #534: GitHub Action that checks, if a suitable Makrdown file is present or not, then look for errors in Markdown File.
# Description

Just like #495 I believe that a similar Action fore `README.md` files can be a good enhancement for the Repo.

## Language

- [x] Javascript
- [x] Python
- [x] YAML

## Type of issue

- [x] Feature

## Checklist:

- **For Feature**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| MarkDown Lint Github Action | A GitHub action that can check and Lint `README.md` | feature, SLoP | @vybhav72954  |

**Is your feature request related to a problem? Please describe.**: Cross-checking the Markdown files must be a painful task for the Admins, and even after that, many times there are spelling mistakes and broken links in the `md` file.
**Describe the solution you'd like**: A JavaScript or Python code to Lint an `md` file. A Github action to trigger 2 scripts - 

- To check if there is `md` file.
- Lint that `md` file

**Additional context**: Ignore the `up-for-grabs` label.

### LINKED ISSUE #697: Spell Check Markdown Github Action
**Is your feature request related to a problem? Please describe.**
We need a GitHub action to check the spellings, trust me we need it because I have done this 3 times already (#459, #523, #567).

Still just today I found a few problems, we need to format the old code base ourselves, but having an action to point out problems is never a bad idea.

**Describe the solution you'd like**
A GitHub action, strict enough to find every small mistake and flexible enough to ignore Coding Terminologies (e.g. JavaScript is a typo but not a typo at the same time).

**Describe alternatives you've considered**
Using spellchecking software and libraries I guess, not the best solution.

**Additional context**
Ignoring the required words is key.

### PR DESCRIPTION
**Pull request by vybhav72954**
# Description

## Added 3 actions and corresponding files

I have added 4 actions (3 `yml` files) and their corresponding required files. 

The list of added files are - 

- md_lint.yml (For Linting YAML and MD)
- md_link.yml (Link Checking)
- md_spell.yml (Spell Checking)
- .markdown-lint.yml (Config file for md_lint)
- mlc_config.json (Config file for md_link)
- .spellcheck.yml (Config file for md_spell)
- .wordlist.txt (Dictionary for ignoring terms, useful for me_spell)
- Troubleshoot.md (A guide for all the above actions)

Fixes #697 
Fixes #534 
Fixes #401 

Although the README (Troubleshoot.md) has enough information, considering these actions are powerful, I request @HarshCasper and other maintainers to kindly ask me anything and/or suggest me anything on the Discussion Forum, quick link - #672 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) (Not right now, but I have a plan for the future)
- [x] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by vybhav72954** [comment]
@HarshCasper I will add a few SS as well here only, for some reason, Pastebin and ImgBB links are not working in `md` files, are you aware of the reason perhaps?

**Comment by vybhav72954** [comment]
@HarshCasper I purposefully allowed all the 3 actions to run on the whole codebase once. You can see the amount of errors generated. 

i don't think we need any screenshot after all?

**Comment by vybhav72954** [comment]
@HarshCasper Am moving this to draft, I think one small addition is still possible, meanwhile, you can go through the code

**Comment by vybhav72954** [comment]
@HarshCasper Can you review?

**Comment by HarshCasper** [comment]
LGTM! 

I will merge this for now, but I would look to see if there are any bugs arising in the future. Thank for this great work @vybhav72954 !

**Comment by vybhav72954** [comment]
> LGTM!
> 
> I will merge this for now, but I would look to see if there are any bugs arising in the future. Thank for this great work @vybhav72954 !

I will also keep an eye on it.

**Pull request merged**
