### PR TITLE
Script addition : LinkedIn endorsements

### LINKED ISSUE #1022: Script to scrap LinkedIn Endorsements
# Description

Create a Script to scrap LinkedIn Endorsements and see who has endorsed you in what technologies. 

## Language

- [X] Golang
- [X] Javascript
- [X] Python
- [X] BASH

### PR DESCRIPTION
**Pull request by jhamadhav**
# Description

**linkedin_endorsements** is a script that scrapes LinkedIn Endorsements and sees who has endorsed someone in what technologies.

Fixes #1022 

## Type of change

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

# Output

linkedinEndorsement

### CODE REVIEW

**Comment by jhamadhav** [comment]
@HarshCasper @vybhav72954 Please review the PR

**Review by vybhav72954 — CHANGES_REQUESTED** [review]
The script looks good but I need approval from other mentors as well for this one.

Meanwhile, Cann you please update the path of this on the JavaScript README? (One that's inside the JavaScript) folder.

**Comment by jhamadhav** [comment]
> 
> 
> The script looks good but I need approval from other mentors as well for this one.
> 
> Meanwhile, Cann you please update the path of this on the JavaScript README? (One that's inside the JavaScript) folder.

sure!

**Comment by jhamadhav** [comment]
@vybhav72954 It been quite a while, any update regarding this PR? has it been reviewed by others?

**Review by HarshCasper — APPROVED** [review]

**Pull request merged**
