### PR TITLE
Fixed issue 830

### LINKED ISSUE #830: Broken Link and Name in Python Folder
# Description 
In the `/Python` folder, the dir - [Merge_2_PFDs](https://github.com/HarshCasper/Rotten-Scripts/tree/master/Python/Merge_2_PFDs) is misspelled accidentally. This has perhaps caused error while accessing the link from the `README.md` file list of the scripts in Python.

Please look into this and resolve:
- Rename the Directory as `Merge_2_PDFs`
- In that folder, there is a file named `Readme.MD`. Change it to `README.md` to follow good naming style.
- Check and confirm that this Script has a reference listed properly in the table of README.md in the Python Directory.
- If not, then please resolve accordingly.

Feel free to ask any queries re: issue. This must a quick fix.

### PR DESCRIPTION
**Pull request by ElMarchk0**
# Description

Fixed the name of Merge_2_PDFs folder, the name of README.md in that Merge_2_PDFs file and the relevant link in README.md in the Python foldeer

Fixes #830 

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)

- [ ] Documentation Update

# Checklist:

- [ x] My code follows the style guidelines(Clean Code) of this project
- [ x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [x ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by HarshCasper** [comment]
Hi @ElMarchk0 

Can you please comment on the Issue so that I can assign it to you? We don't accept PRs from people who have not been assigned that Issue, but since it is a small patch we can make an exception.

**Comment by vybhav72954** [comment]
@ElMarchk0 You were not assigned this issue, nor you were the first one to comment, @HarshCasper If the person who commented first wants to work on this, we should allow them to make PR and close this

**Comment by vybhav72954** [comment]
@ElMarchk0 Am sorry but the PR is lacking a few important things, first of all, renaming the README was important, but it wasn't done.

Secondly, someone else commented on the issue beforehand, for that reason, I cant assign the issue to you, and moreover, you opened a PR without informing us, I am thankful for your efforts, but it would be better if you mention your interest in an issue beroehand by commenting on it and getting it assigned.

Please find more open issue get them assigned and make a new PR, it would be great to have contributions from your side, I would be waiting :)

**Comment by ElMarchk0** [comment]
My apologies @HarshCasper and @vybhav72954 , I'm pretty new to this and I will be much more careful in the future. Thanks for being so easy going.

**Pull request closed without merging**
