### PR TITLE
Duplicate Image Search and Delete

### LINKED ISSUE #130: Create a Script to find Similar Images in the Directory
# Description

Create a Script to find Similar Images in the Directory

## Language

- [X] Javascript
- [X] Python
- [X] Golang

## Type of issue

*Please delete options that are not relevant.*

- [X] Feature

## Checklist:

- **For Feature**

|name|about|labels|assignees|
|----|-----|------|---------|
|Find Similar Images in Directory|Find Similar Images and remove duplicated Images|Hard, Python, JS, Golang, PSOC'2020|`Open to PSOC'20 Participants`|

**Is your feature request related to a problem? Please describe.**: I always find similar Images in my Directory and I am looking for a way to flush out the duplicated messages.

**Describe the solution you'd like**: You can check out this [Stackoverflow Thread](https://stackoverflow.com/questions/75891/algorithm-for-finding-similar-images) to find the perfect solution to this issue.

**Additional context**: None

### PR DESCRIPTION
**Pull request by vybhav72954**
# Description

A simple and interactive Python Script to delete similar images in a stand-alone directory or compare multiple directories to find duplicates and delete them (optionally).

Fixes #130 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by HarshCasper** [comment]
Can you please delete all the Image Files that you have added an example? I will be looking at your Code thereafter

**Comment by vybhav72954** [comment]
@HarshCasper Done

**Comment by HarshCasper** [comment]
LGTM!

**Comment by HarshCasper** [comment]
give @vybhav72954 150 points

**Pull request merged**
