### PR TITLE
Sending emails in python added

### PR DESCRIPTION
**Pull request by Namyalg**
- The script is written in Python
- Enables sending emails via the SMTP module

### CODE REVIEW

**Comment by HarshCasper** [comment]
Create Dynamic Inputs so that a Script User can input the values. To make things even simpler, you can try to add Flags to allow the User even more functionality to use the Script.

**Comment by Namyalg** [comment]
Okay, but content could be confidential , so I didnt want to include
dynamic input.

**Comment by HarshCasper** [comment]
Make it Dynamic. There must be no issues with confidentiality. Otherwise, it would just remain a Code Stub and a User would not be able to make use of it without going into the Code.

**Comment by Namyalg** [comment]
Yes , okay I will include dynamic input

**Comment by HarshCasper** [comment]
Reviewed and Merged 🙌

Thanks for your Contribution 🎉🤗

**Pull request merged**
