### PR TITLE
Added codeforces problem scrapper

### LINKED ISSUE #291: CodeForces Problem Scrapper
# Description
Develop a python script that should scrape the problem statement into a PDF File with a given problem code from the code forces website. The script should scrape the following items:

1. Problem Statement
2. Images (If any are mentioned in the problem statement)
3. Given Input and Output of the problem statement. 

## Language

- [x] Python

## Type of issue

- [x] Feature

### PR DESCRIPTION
**Pull request by AkM-2018**
# Description

Finds the codeforces problem from the site and saves the problem statement as pdf.

Fixes #291 

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by srimani-programmer — CHANGES_REQUESTED** [review]
Don't convert the image into a PDF because when the image is converted into PDF when the user wants to copy the content it will not be possible. So please scrape the problem content and input and output values as well. If there is an image in the problem statement then you need to download it and add it to the PDF as structured in the Problem statement.

**Comment by AkM-2018** [comment]
If I just scrape the problem content (which is just the HTML) it will lose its styling. Will it be okay?

**Comment by srimani-programmer** [comment]
Yeah, Obvioulsly it will loss the styling but you need to format it while it is adding in the PDF format. I hope you got the point please let me know if you have any issues.

**Comment by AkM-2018** [comment]
Ya, I got your point. I'll push the changes once its done

**Comment by HarshCasper** [comment]
@AkM-2018 Are you working on this?

**Comment by AkM-2018** [comment]
Yes, currently working on it

**Pull request closed without merging**
