### PR TITLE
Corrected typos in various files. Updated Python->README

### LINKED ISSUE #459: Minor typos in README.md Files
# Description

A few files like CONTRIBUTING.md have some minor typo errors, considering there are a few First timers here too, I think they should be corrected.

## Language

- [ ] Other (Markdown, HTML)

## Type of issue

_Please delete options that are not relevant._

- [ ] Bug

- **For Bug**

| name | about                                     | labels | assignees                                                      |
| ---- | ----------------------------------------- | ------ | -------------------------------------------------------------- |
| Typo in ReadMe | Minor Typos in README that can lead to errors | SLoP | @vybhav72954 |

Admins or the maintainers can also sort them out on their own.

### PR DESCRIPTION
**Pull request by vybhav72954**
# Description

There were errors in CONTRIBUTING.md and a few README files. I corrected
them. Moreover, I updated my accepted contribution in Python->README.md

Update - *9 October* Corrected all the files except Javascript
Fixes #459 

## Type of change

_Please delete options that are not relevant._

- [x] Documentation Update

# Checklist:

Not Applicable

### CODE REVIEW

**Comment by HarshCasper** [comment]
Can you squash all your commits into a single Commit?

**Comment by vybhav72954** [comment]
> Can you squash all your commits into a single Commit?


I won't be lying if I say that am not sure how to do that, lemme try.

**Comment by vybhav72954** [comment]
> > Can you squash all your commits into a single Commit?
> 
> I won't be lying if I say that am not sure how to do that, lemme try.

@HarshCasper Si I tried doing that using Git CLI

i used `git rebase -i` to selectively squash commits.

The problem I faced is 

- on running the command on Typo branch. It is giving me a empty text editor.

- If I reset the head of master to Typo and run the command on the Master breach. I get the expected result where I can Squash the commits in one (But on master branch) .

**So 2 things, either you can squash the commits while merging, or I can squash them myself but on the master branch**

**Comment by vybhav72954** [comment]
@HarshCasper I squashed the commit, for some reason I feel I messed up the commit History, can you ensure if that's the case or not?

If that's the case, close this PR with an apt label. I will do a soft reset to issue a new PR

**Comment by seema1711** [comment]
@HarshCasper I have reviewed all files.

**Comment by HarshCasper** [comment]
give @vybhav72954 25 points

**Pull request merged**
