### PR TITLE
Internships-Scraper

### PR DESCRIPTION
**Pull request by twozero88**
# Description
Added a script to scrape internships from Internshala to a csv file.

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by twozero88** [comment]
@HarshCasper I don't understand '1 failing Check'. Could you help me out here?

**Comment by HarshCasper** [comment]
@all-contributors bot please add @twozero88 for code

**Comment by HarshCasper** [comment]
@all-contributors bot please add @twozero88 for documentation

**Comment by twozero88** [comment]
Thanks for the merge @HarshCasper

**Pull request merged**
