### PR TITLE
Update pr workflow #756

### LINKED ISSUE #756: CLI Script to understand PR Workflows
# Description

Create a CLI Script which can help us better understand the Pull Request Workflows on the Project with some important statistics: 

- How many PRs are open? 
- How long have the PRs been open? 
- Number of Comments on open PRs? 
- Merged and Closed PRs

You can come up with your own customization on what you are aiming to build. Some good resources to check out on how to build this can be found on the [Pull Request API](https://developer.github.com/v3/pulls/) by Github.

## Language

- [X] Python
- [X] Golang
- [X] Javascript

## Checklist:

- **Details on the Script**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| PR Workflow | CLI to fetch PR information and their status quo | MWOC, hard, Python, Javascript, Golang |  |

### PR DESCRIPTION
**Pull request by rahulraikwar00**
# Description
`pwr` is Pull Requests Workflow on the command line. It brings OPEN, CLOSED,MERGED and other PR concepts to the terminal next to where you are already working with `git` and your code.

Fixes #756
@HarshCasper 
@vybhav72954 

## Type of change

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by rahulraikwar00** [comment]
@seema1711 @HarshCasper @vybhav72954 can you please review my pr !

**Review by sohamsshah — APPROVED** [review]
Looks good to me. It is ready to merge from my side 🙌

**Comment by vybhav72954** [comment]
@rahulraikwar00 some of your commits are coinciding with the changes we made in `CONTRIBUTING.md`. This is most probably because of the force push you did. Can you sort that out?

**Comment by rahulraikwar00** [comment]
@HarshCasper  i'm not sure and don't know how to resolve this.!can you please guide me ?

**Comment by vybhav72954** [comment]
> @HarshCasper i'm not sure and don't know how to resolve this.!can you please guide me ?

Hey Rahul, there are multiple conflicts. I went though the Git History and was unable to find any conflicts from your branch.

Can you please do one thing?

run command ```git branch -r --contains``` in your branch `prwrkflow2` and show us the output here

**Comment by rahulraikwar00** [comment]
@vybhav72954  
output:
origin/prwokflowv2 
Screenshot_git branch -r --contains_2


i found something strange here, or may be i don''t know !
see

Screenshot_git log --graph --oneline_2

same commits but different commit id.

**Review by vybhav72954 — CHANGES_REQUESTED** [review]
Hey Rahul, I don't think rebasing the head would work now.

Let me tell you what possibly happened anyways, the branch you made for this PR wasn't up to date with the upstream (the master on GitHub).

You must have updated this branch with upstream but possibly using `git merge`?

In any case, can you make a new branch from **master**, and add your changes again. 

I would recommend deleting your fork as well, although the master of your fork looks good, and is not required but is still recommended from my side at least.

**Comment by rahulraikwar00** [comment]
@vybhav72954 ok.. i'm going to close this pr and gonna make new pr with fresh forked repo ..is it fine?

**Comment by vybhav72954** [comment]
Migrated to #894

**Pull request closed without merging**
