### PR TITLE
search queries on wikipedia

### LINKED ISSUE #1149: searching queries on wikipedia from console/IDE
# Description

This method can automate our work of searching something on wikipedia using voice.

| name            | problem/motivation                                                  | possible solution  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| searching Wikipedia | to search any topic easily and fast | I will be using a wikipedia library for searching about any topic on Wikipedia. I will be doing this using python | self-assign |

### PR DESCRIPTION
**Pull request by Umesh-01**
# Description

I have added a feature for searching queries on Wikipedia. We can search for any topic/query available in Wikipedia database, for example- ISRO on Wikipedia. For this feature I have used Wikipedia library.

This fixes #1149 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by RohiniRG** [comment]
We already have a very similar script for PR #1160 and the implementation doesn't seem much different or intuitive.
@HarshCasper @vybhav72954 @iamakkkhil should we continue with this PR?

**Comment by Umesh-01** [comment]
> We already have a very similar script for PR #1160 and the implementation doesn't seem much different or intuitive.
> @HarshCasper @vybhav72954 @iamakkkhil should we continue with this PR?

@RohiniRG yes, it is looking similar because of the voice functionality but with this feature we can search any query on Wikipedia, it is useful.

**Comment by Umesh-01** [comment]
> We already have a very similar script for PR #1160 and the implementation doesn't seem much different or intuitive.
> @HarshCasper @vybhav72954 @iamakkkhil should we continue with this PR?

@RohiniRG It is useful and totally different. There is another way, If I remove the voice functionality then user will search their queries by typing instead of using voice command. Should I remove the voice functionality??

**Comment by HarshCasper** [comment]
@Umesh-01 I use scripts almost all day for my tasks and work. I rarely use any voice functionality. I don't understand the use-case of adding voice detection, which might look fancy but doesn't fit anywhere. 

Almost all of your PRs have added/forced this voice feature which is a blocker for us to test and validate them properly.

**Comment by Umesh-01** [comment]
I have done some changes and removed the voice functionality feature

**Comment by Umesh-01** [comment]
now check it @HarshCasper @RohiniRG @vybhav72954

**Review by HarshCasper — CHANGES_REQUESTED** [review]
I don't find any specific novelty in this script. It is using a pre-defined package that abstracts the whole thing and uses voice as the medium to communicate which is not even accessible. I am not inclined to accept this PR.

**Pull request closed without merging**
