### PR TITLE
Adding audiobook script

### LINKED ISSUE #1406: [feature request]:
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the feature.

I want to contribute to a project for Reading/Saving audiobooks.  You can listen to your book and also can save it to listen to it later.

Supported Format:- 

1. Pdf
2. txt 
3. Epub

### Problem/Motivation.

sometimes it's better to listen.

### Possible Solution/Pitch.

it will convert the input file into the common JSON format then the user can read it or save it.

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by codeperfectplus**
# Description

Added a script to Read Book in audiobook folder.

Fixes #1406

## Type of change

- [X] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy-to-understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by codePerfectPlus** [comment]
Please merge it after 31 October.

**Comment by ClasherKasten** [comment]
> Please merge it after 31 October.

That's possible, but can I ask what the reason is for this request? (Sorry if I am a little too curious).

**Review by ClasherKasten — CHANGES_REQUESTED** [review]
Overall, this is just like an example and documentation for the [audiobook](https://pypi.org/project/audiobook/) library. This is a repository for useful scripts and not a place to promote self-created libraries.
My point here is mainly the `README.md`. It's just the same as [audiobooks](https://pypi.org/project/audiobook/) `README.md`. But it shouldn't be that. The `README.md` for this script should be about the the script that you want to add and not about the library behind it.
You can also read about this in the `STYLE_GUIDELINES.md` under section **"Prerequisites"**.
If you need inspiration for the `README.md` take a look at `TEMPLATE_README.md` file.

`script.py` itself looks OK to me.

**Comment by codePerfectPlus** [comment]
> Overall, this is just like an example and documentation for the [audiobook](https://pypi.org/project/audiobook/) library. This is a repository for useful scripts and not a place to promote self-created libraries. My point here is mainly the `README.md`. It's just the same as [audiobooks](https://pypi.org/project/audiobook/) `README.md`. But it shouldn't be that. The `README.md` for this script should be about the the script that you want to add and not about the library behind it. You can also read about this in the `STYLE_GUIDELINES.md` under section **"Prerequisites"**. If you need inspiration for the `README.md` take a look at `TEMPLATE_README.md` file.
> 
> `script.py` itself looks OK to me.

Thanks for pointing out the issues. I will make the necessary changes.

**Comment by codePerfectPlus** [comment]
> > Please merge it after 31 October.
> 
> That's possible, but can I ask what the reason is for this request? (Sorry if I am a little too curious).

I am participating in Hacksquad so I can only make quality PR. Otherwise, I can be disqualified. That's why I was asking to merge it after 31st October.
😁

**Comment by ClasherKasten** [comment]
As I reviewed this PR the first time I thought that this would be a very cool addition to the project.
Problem:
> I am participating in Hacksquad so I can only make quality PR. Otherwise, I can be disqualified. That's why I was asking to merge it after 31st October.
:grin:

You state yourself that this is not a quality PR. And even if I think this script would be worth adding, I don't think this project aims to be a collections basin for unqualitative PRs and scripts.
Is there anyone from the other maintainers (@HarshCasper, @iamakkkhil, @sohamsshah, @seema1711, @vybhav72954, @RohiniRG) who has an (other) opinion on this?

**Comment by codePerfectPlus** [comment]
but it's a very helpful script to convert the book to audio format. so, In my opinion, it's worth it. I mentioned the quality PR which means contribution to the collections repo and DSA repo are not allowed

**Comment by ClasherKasten** [comment]
> I mentioned the quality PR which means contributions to the collections repo and DSA repo are not allowed

Following this argument, you already should be disqualified for opening PRs in [awesomeScripts](https://github.com/Py-Contributors/awesomeScripts) as this is basically the same as this project. So I personally don't see any reason for merging it before 31. October.

**Comment by codePerfectPlus** [comment]
> > I mentioned the quality PR which means contributions to the collections repo and DSA repo are not allowed
> 
> Following this argument, you already should be disqualified for opening PRs in [awesomeScripts](https://github.com/Py-Contributors/awesomeScripts) as this is basically the same as this project. So I personally don't see any reason for not merging it before 31. October.

I got warnings for that. No issue you can merge it.

**Comment by ClasherKasten** [comment]
> I got warnings for that. No issue you can merge it.

I didn't no this. Now the situation is understandable, I guess this doesn't gonna get merged before 31st October.

**Comment by codePerfectPlus** [comment]
> > I got warnings for that. No issue you can merge it.
> 
> I didn't no this. Now the situation is understandable, I guess this doesn't gonna get merged before 31st October.

Thanks @ClasherKasten

**Pull request closed without merging**
