### PR TITLE
script for keeping PC awake added

### LINKED ISSUE #824: Script to keep PC awake
# Description

A script to make the PC avoid going into standby mode.
The script will automatically perform mouse clicks and keystrokes which will keep the PC awake and the user need not worry about the PC entering into standby mode.

## Language

- [ ] Bash
- [ ] Go
- [ ] Python

## Checklist:

- **Details on the Script**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Keep PC awake | This script will make sure the PC avoids getting into standby mode | GSSoC'21 | @ayushjain2205 |

### PR DESCRIPTION
**Pull request by Ayushjain2205**
# Description

Python script added to keep PC awake 

Fixes #824 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by seema1711** [comment]
I ran the script, but it didn't work for me, do we need to do anything specific?

**Review by HarshCasper — CHANGES_REQUESTED** [review]
It doesn't work for me as well. Can you add a GIF or a demo or some clear instructions on how to replicate this on our local machine?

**Comment by Ayushjain2205** [comment]
screenrecording

This is a working demo video. The default time after which the script ran was 3 minutes and I forgot to mention about the command line arguments in the readme. Appologies for this mistake.

To make is easier to test, I will change the default value to 1 second and update the Readme and make a PR.

Nothing needs to be configured on the local machine only the required packaged needs to installed and you need to wait for **1 minute** to see the mouse moving automatically on the left side.

**Review by rahulraikwar00 — CHANGES_REQUESTED** [review]
@HarshCasper I've seen this code before Somewhere... let me check if I can find the orignal author.

**Comment by vybhav72954** [comment]
> @HarshCasper I've seen this code before Somewhere... let me check if I can find the orignal author.

@rahulraikwar00 Am already aware of that 👍🏻 The PR is under review for plag

**Comment by rahulraikwar00** [comment]
@HarshCasper  here' https://github.com/Johnson468/Stay-Awake/blob/master/src/awake.py

**Comment by vybhav72954** [comment]
LOL @Ayushjain2205 PLease don't indulge in plagiarism, we don't support that.

Let me clarify why your post wants flagged earlier, I found [this](https://gist.github.com/rav1and3/ede1c2aee516a71fe4b762ab025544f1)
which of course isn't the actual source (it is a gist after all) But Rahul found out the actual source as well. 

We encourage contributions from everyone, find other open issues but please stop copy-pasting, that's not what OSS and GSSoC are about.

**Pull request closed without merging**
