### PR TITLE
Script to launch an EC2 Instance - Go

### LINKED ISSUE #433: Script to launch an EC2 Instance
# Description

Create a Script that allows you to create any number of AWS EC2 Instances that you wish to create. You need to specify all your Credentials in a `.env` file which includes your Access Key, Secret Key, Region, Zone, Instance Type and more.

## Language

- [X] Python
- [X] Javascript
- [X] Golang

## Type of issue

_Please delete options that are not relevant._

- [X] Feature

### PR DESCRIPTION
**Pull request by frbimo**
# Description

EC2 Launcher with number of instance as input argument.

Fixes #433

## Type of change

_Please delete options that are not relevant._

- [X] New feature (non-breaking change which adds functionality)

# Checklist:

- [X] My code follows the style guidelines(Clean Code) of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by frbimo** [comment]
@HarshCasper PTAL

**Comment by HarshCasper** [comment]
LGTM! Thanks for your contribution 💥🎉

**Comment by HarshCasper** [comment]
@all-contributors bot please add @frbimo for code

**Comment by HarshCasper** [comment]
@all-contributoes bot please add @frbimo for documentation

**Comment by HarshCasper** [comment]
@all-contributors bot please add @frbimo for documentation

**Pull request merged**
