### PR TITLE
Added Discord_Bot

### LINKED ISSUE #417: Discord Bot
# Description

Make a  discord bot with moderation and information commands which is very easy to setup

# Language

- [x] Python

# Type of Issue

- [x] Feature

### PR DESCRIPTION
**Pull request by KILR007**
# Description

Simple Discord Bot

Fixes #417 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by HarshCasper** [comment]
I would like to see a GIF/Screen Record of your implementation before the Code Review and Merging Part.

**Comment by HarshCasper** [comment]
Are you working on the same @KILR007 ?

**Comment by KILR007** [comment]
Indeed I am, Just Busy IRL at this point

**Comment by KILR007** [comment]
Here I Added It!
Sorry For Delay'\

**Comment by HarshCasper** [comment]
Looks oddly good to me! 

Thanks 🎉

**Pull request merged**
