### PR TITLE
added a feature for speech recognizer

### LINKED ISSUE #1148: speech recognizer using python
# Description

I want to make a speech recognizer using Python. With this human voice can be converted into text. It uses speech recognition module to do this job.

| name            | problem/motivation                                                  | possible solution  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| speech recognizer | to convert speech into text | yes, I will be using a speech recognizer api for this task | self-assign |

### PR DESCRIPTION
**Pull request by Umesh-01**
# Description

Added a feature to recognize the user's voice with the help of speech recognition library and pyttsx3 in Python. 
  
This fixes #1148 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Umesh-01** [comment]
Hey @iamakkkhil , duplicate :neutral_face:
what do u mean by duplicate tag??
It's not duplicate go to issue #1148 I have explained there...

if two mobile phones are using touch screen display it doesn't mean they are duplicate... :grimacing:

**Comment by HarshCasper** [comment]
Hi @Umesh-01 

Can you be a little polite during the discussion? 

Moreover, GitHub discussions require a professional understanding and conversation. It is not similar to how we talk over WhatsApp/Telegram and certainly won't tolerate ill words against any of the fellow contributors or maintainers. 

While your PR https://github.com/HarshCasper/Rotten-Scripts/pull/1160 is acceptable for a review, this PR of yours is not. It is exactly doing what the library/module that you are using is supposed to do. There is nothing innovative or intuitive about the same. 

I would certainly advise you to close this PR since its too "basic" and focus your energy on #1160 where I will be doing a detailed review.

**Comment by Umesh-01** [comment]
> Hi @Umesh-01
> 
> Can you be a little polite during the discussion?
> 
> Moreover, GitHub discussions require a professional understanding and conversation. It is not similar to how we talk over WhatsApp/Telegram and certainly won't tolerate ill words against any of the fellow contributors or maintainers.
> 
> While your PR #1160 is acceptable for a review, this PR of yours is not. It is exactly doing what the library/module that you are using is supposed to do. There is nothing innovative or intuitive about the same.
> 
> I would certainly advise you to close this PR since its too "basic" and focus your energy on #1160 where I will be doing a detailed review.

okk @HarshCasper , but I already asked you while creating these issues...
and you haven't replied and I started working on these issues...

**Comment by Umesh-01** [comment]
@HarshCasper can u tell me now, should I work on issue #1149 ??

**Comment by HarshCasper** [comment]
Hi @Umesh-01 

There is a reason why we have 5 maintainers for the project. I am not able to tend to every issues and PR on the project that is happening (I keep my GitHub E-Mails on Spam because there's a ton of them) 

That should not stop you but get in touch with other maintainers and get the things done. I would mostly give a final review or merge the PR. 

I would refrain from working on any Voice-based scripts. Though they have some interesting use-cases, I rarely see anyone using them up. You can instead work on scripts that require more intuition and can help solve real-world use cases.

**Comment by Umesh-01** [comment]
Hello @HarshCasper 
I would like to give you an advice you people (maintainers or admins) should manually assign issues so that the contributors could know what to work on or what not...

**Comment by Umesh-01** [comment]
because @HarshCasper I can understand it is not possible to go through each email, there are many emails for each action on github like for this comment also you would get a mail but you can go for issues so that contributors after making a PRs won't face these type of difficulties...

**Comment by HarshCasper** [comment]
> Hello @HarshCasper
> I would like to give you an advice you people (maintainers or admins) should manually assign issues so that the contributors could know what to work on or what not...

Noted!

**Review by HarshCasper — CHANGES_REQUESTED** [review]
We won't be able to accept this PR. It is still rudimentary and does not do anything novel. At the barebones, it is just taking a voice input and spitting that out. I don't see what value it would bring. 

You can take up the other open issues on the list.

**Pull request closed without merging**
