### PR TITLE
Fixed some grammatical errors

### PR DESCRIPTION
**Pull request by rohankumawat**
## Description

There were some grammatical errors in the README.md file. Fixed them up and changed some of the sentences which might seem more appealing to the viewer or the contributor. 

## Type of change

_Please delete options that are not relevant._

- [x] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by rohankumawat** [comment]
Hi!
Can anyone tell me why all the checks are being failed?
How to solve this issue?

**Comment by HarshCasper** [comment]
LGTM!

**Comment by HarshCasper** [comment]
@all-contributors bot please add @rohankumawat for documentation

**Comment by rohankumawat** [comment]
Thank you 😄

**Pull request merged**
